import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        // Library theme tokens (separate namespace)
        'lib-primary': 'var(--lib-color-primary)',
        'lib-primary-hover': 'var(--lib-color-primaryHover)',
        'lib-primary-active': 'var(--lib-color-primaryActive)',
        'lib-primary-foreground': 'var(--lib-color-primaryForeground)',
        'lib-secondary': 'var(--lib-color-secondary)',
        'lib-secondary-hover': 'var(--lib-color-secondaryHover)',
        'lib-secondary-active': 'var(--lib-color-secondaryActive)',
        'lib-secondary-foreground': 'var(--lib-color-secondaryForeground)',
        'lib-accent': 'var(--lib-color-accent)',
        'lib-accent-hover': 'var(--lib-color-accentHover)',
        'lib-accent-active': 'var(--lib-color-accentActive)',
        'lib-accent-foreground': 'var(--lib-color-accentForeground)',
        'lib-background': 'var(--lib-color-background)',
        'lib-foreground': 'var(--lib-color-foreground)',
        'lib-card': 'var(--lib-color-card)',
        'lib-card-foreground': 'var(--lib-color-cardForeground)',
        'lib-muted': 'var(--lib-color-muted)',
        'lib-muted-foreground': 'var(--lib-color-mutedForeground)',
        'lib-border': 'var(--lib-color-border)',
        'lib-input': 'var(--lib-color-input)',
        'lib-ring': 'var(--lib-color-ring)',
        'lib-success': 'var(--lib-color-success)',
        'lib-success-foreground': 'var(--lib-color-successForeground)',
        'lib-warning': 'var(--lib-color-warning)',
        'lib-warning-foreground': 'var(--lib-color-warningForeground)',
        'lib-error': 'var(--lib-color-error)',
        'lib-error-foreground': 'var(--lib-color-errorForeground)',
        'lib-info': 'var(--lib-color-info)',
        'lib-info-foreground': 'var(--lib-color-infoForeground)',
      },
      fontFamily: {
        sans: ["var(--font-nunito)", "var(--font-noto-kr)", "system-ui", "sans-serif"],
        nunito: ["var(--font-nunito)", "system-ui", "sans-serif"],
        noto: ["var(--font-noto-kr)", "system-ui", "sans-serif"],
        mono: ["var(--font-anonymous-pro)", "ui-monospace", "monospace"],
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-in-left": "slideInLeft 0.3s ease-out",
        "slide-in-right": "slideInRight 0.3s ease-out",
        "chameleon": "chameleon 20s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideInLeft: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        slideInRight: {
          "0%": { transform: "translateX(10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
      },
      spacing: {
        'lib-xs': 'var(--lib-spacing-xs)',
        'lib-sm': 'var(--lib-spacing-sm)',
        'lib-md': 'var(--lib-spacing-md)',
        'lib-lg': 'var(--lib-spacing-lg)',
        'lib-xl': 'var(--lib-spacing-xl)',
        'lib-2xl': 'var(--lib-spacing-2xl)',
        'lib-3xl': 'var(--lib-spacing-3xl)',
        'lib-4xl': 'var(--lib-spacing-4xl)',
        'lib-5xl': 'var(--lib-spacing-5xl)',
        'lib-6xl': 'var(--lib-spacing-6xl)',
      },
      borderRadius: {
        'lib-none': 'var(--lib-radius-none)',
        'lib-sm': 'var(--lib-radius-sm)',
        'lib-md': 'var(--lib-radius-md)',
        'lib-lg': 'var(--lib-radius-lg)',
        'lib-xl': 'var(--lib-radius-xl)',
        'lib-2xl': 'var(--lib-radius-2xl)',
        'lib-full': 'var(--lib-radius-full)',
      },
      fontFamily: {
        'lib-sans': ['var(--lib-font-sans)', 'system-ui', 'sans-serif'],
        'lib-mono': ['var(--lib-font-mono)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'lib-xs': ['var(--lib-font-size-xs)', { lineHeight: 'var(--lib-line-height-xs)' }],
        'lib-sm': ['var(--lib-font-size-sm)', { lineHeight: 'var(--lib-line-height-sm)' }],
        'lib-base': ['var(--lib-font-size-base)', { lineHeight: 'var(--lib-line-height-base)' }],
        'lib-lg': ['var(--lib-font-size-lg)', { lineHeight: 'var(--lib-line-height-lg)' }],
        'lib-xl': ['var(--lib-font-size-xl)', { lineHeight: 'var(--lib-line-height-xl)' }],
        'lib-2xl': ['var(--lib-font-size-2xl)', { lineHeight: 'var(--lib-line-height-2xl)' }],
        'lib-3xl': ['var(--lib-font-size-3xl)', { lineHeight: 'var(--lib-line-height-3xl)' }],
        'lib-4xl': ['var(--lib-font-size-4xl)', { lineHeight: 'var(--lib-line-height-4xl)' }],
      },
    },
  },
  plugins: [],
};

export default config;
