'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getFontClass: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.foundations': 'Foundations',
    'nav.brand': 'Brand',
    'nav.product': 'Product',
    'nav.team': 'Team',
    'nav.tools': 'Tools',
    'nav.sections.mission': 'The Mission',
    'nav.sections.philosophy': 'Our Mindset',
    'nav.sections.values': 'Working Principles',
    'nav.sections.team': 'Our Team',
    'nav.sections.tools': 'Our Stack',
    
    // Contact Banner
    'banner.title': 'Want to meet us over coffee?',
    'banner.cta': 'Schedule a meeting',
    'banner.cta.short': 'Contact',
    'banner.requirements.schedule': 'Schedule a time',
    'banner.requirements.info': 'Include your info',
    
    // Hero
    'hero.title': 'Buzzvil Design',
    'hero.subtitle': 'Engaging. Playful. Scalable.',
    'hero.sentence.start': 'We build',
    'hero.sentence.end': 'experiences.',
    'hero.keyword.engaging': 'Engaging',
    'hero.keyword.playful': 'Playful',
    'hero.keyword.scalable': 'Scalable',
            'hero.explore': 'Explore Foundations',
            'hero.brand': 'Brand',
            'hero.product': 'Product',
            'hero.scroll': 'Scroll to explore',
    
            // Mission & Vision
            'mission.title': 'Mission & Vision',
            'mission.subtitle': 'Our mission and vision guide everything we do at Buzzvil.',
            'mission.mission.title': 'Mission',
            'mission.mission.subtitle': 'what we do now',
            'mission.mission.content': 'We design meaningful interactions that shape how people discover, experience, and stay connected with Buzzvil\'s campaigns and brand.\nOur goal is to turn advertising into experiences people choose to explore—moments that capture attention, spark curiosity, and drive real results for advertisers.',
            'mission.vision.title': 'Vision',
            'mission.vision.subtitle': 'what future we\'re building',
            'mission.vision.content': 'We set the next standard for AdTech design by transforming ads and brand touchpoints into engaging, repeatable experiences that connect users and advertisers.\nWe envision a future where advertising feels natural, enjoyable, and seamlessly part of everyday life.',
    
            // Philosophy
            'philosophy.title': 'Philosophy',
            'philosophy.subtitle': 'how we approach it',
            'philosophy.content': 'At Buzzvil, design shapes how people experience advertising, not as interruptions, but as moments of connection and delight.\nWe believe every touchpoint, from brand to product, should feel playful, engaging, and effortless.\nOur role is to unify how Buzzvil looks, feels, and behaves across the ecosystem, building trust, driving performance, and inspiring what AdTech can become.',
    
            // Ways of Working
            'waysOfWorking.title': 'Ways of Working',
            'waysOfWorking.subtitle': 'How we think, create, and collaborate at Buzzvil Design.',
            'waysOfWorking.principles.title': 'Our Principles',
            'waysOfWorking.principles.subtitle': 'How we work together to design at Buzzvil.',
            'waysOfWorking.team.title': 'Our Team',
            'waysOfWorking.team.subtitle': 'The people behind Buzzvil Design.',
            'waysOfWorking.stack.title': 'Our Stack',
            'waysOfWorking.stack.subtitle': 'The tools that power our design work.',
    
    // Principles
    'principles.title': 'Principles',
    'principles.subtitle': 'The principles that guide our approach to design and development.',
    'principles.reward.title': 'Reward = Time',
    'principles.reward.shortTitle': 'Reward',
    'principles.reward.content': 'Rewards are a transparent and measurable exchange of user attention. Mechanism: 1P ≈ 1 second of attention. This gives consistency to users and predictability to advertisers.',
    'principles.delight.title': 'Delight Without Deception',
    'principles.delight.shortTitle': 'Delight',
    'principles.delight.content': 'Rewards spark motivation, but experiences sustain engagement. We never use dark patterns: never overlay one ad on another, never mislead, never trap. Interactions must feel playful, clear, and respectful.',
    'principles.scalable.title': 'Scalable by Design',
    'principles.scalable.shortTitle': 'Scalable',
    'principles.scalable.content': 'Every design decision must scale across products, partners, and business models. We provide meaningful customization, but avoid unsustainable exceptions. These principles can veto business or product decisions that fragment the system.',
    
    // Principles Characteristics
    'principles.reward.characteristics.0': 'Transparent Exchange',
    'principles.reward.characteristics.1': 'Measurable Attention',
    'principles.reward.characteristics.2': 'User Consistency',
    'principles.reward.characteristics.3': 'Advertiser Predictability',
    'principles.delight.characteristics.0': 'No Dark Patterns',
    'principles.delight.characteristics.1': 'Playful Interactions',
    'principles.delight.characteristics.2': 'Clear Communication',
    'principles.delight.characteristics.3': 'Respectful Design',
    'principles.scalable.characteristics.0': 'Cross-Product Scale',
    'principles.scalable.characteristics.1': 'Meaningful Customization',
    'principles.scalable.characteristics.2': 'System Integrity',
    'principles.scalable.characteristics.3': 'Decision Veto Power',
    
    // Values
            'values.title': 'Working Principles',
    'values.subtitle': 'How we work together to design at Buzzvil.',
            'values.build.title': 'Build in the Open',
            'values.build.shortTitle': 'Build in the Open',
    'values.build.content': 'We start rough, share early, and iterate fast. Every designer has access to AI tools that accelerate exploration. Feedback and quick loops help us refine ideas into solid, production-ready solutions.',
    'values.build.tagline': 'iterate fast.',
    'values.clarity.title': 'Clarity Through Feedback',
    'values.clarity.shortTitle': 'Be Crystal Clear',
    'values.clarity.content': 'We communicate with candor and precision. Feedback is how we grow: giving it clearly, receiving it openly, and applying it constructively. Clear communication builds trust and avoids wasted effort.',
    'values.clarity.tagline': 'Clarity first, feedback always.',
    'values.grit.title': 'Own it, Ship It',
    'values.grit.shortTitle': 'Own it, Ship It',
    'values.grit.content': 'Designers don\'t just stop at drafts. We take ownership of user stories and projects, pushing them from first sketches through to production. We lead with persistence and craft until the outcome is real.',
    'values.grit.tagline': 'Grit.',
    'values.explore.title': 'Bold Explorers',
    'values.explore.shortTitle': 'Explorers',
    'values.explore.content': 'We embrace research, experimentation, and AI adoption as core to our craft. With powerful tools and a culture of inquiry, we have no excuse not to explore widely, validate rigorously, and design with confidence.',
    'values.explore.tagline': 'Explore boldly, research deeply.',
    'values.team.title': 'One-UX',
    'values.team.shortTitle': 'One-UX',
    'values.team.content': 'We align as a design team before we scale out. That means syncing often, sharing conventions, and applying consistent practices. Our alignment ensures partners, users, and advertisers experience Buzzvil design as one coherent system.',
    'values.team.tagline': 'Align first, scale together.',
    
    // Values Characteristics
    'values.build.characteristics.0': 'Rapid Prototyping',
    'values.build.characteristics.1': 'AI-Powered Exploration',
    'values.build.characteristics.2': 'Early Sharing',
    'values.build.characteristics.3': 'Quick Iteration',
    'values.clarity.characteristics.0': 'Candor & Precision',
    'values.clarity.characteristics.1': 'Open Communication',
    'values.clarity.characteristics.2': 'Constructive Growth',
    'values.clarity.characteristics.3': 'Trust Building',
    'values.grit.characteristics.0': 'Full Ownership',
    'values.grit.characteristics.1': 'End-to-End Delivery',
    'values.grit.characteristics.2': 'Persistence',
    'values.grit.characteristics.3': 'Production Focus',
    'values.explore.characteristics.0': 'Research-Driven',
    'values.explore.characteristics.1': 'AI Adoption',
    'values.explore.characteristics.2': 'Wide Exploration',
    'values.explore.characteristics.3': 'Rigorous Validation',
    'values.team.characteristics.0': 'Team Alignment',
    'values.team.characteristics.1': 'Shared Conventions',
    'values.team.characteristics.2': 'Consistent Practices',
    'values.team.characteristics.3': 'Coherent System',
    
    // Resources
    'resources.title': 'Design Resources',
    'resources.subtitle': 'Everything you need to create exceptional user experiences. Download our latest design files, guidelines, and templates.',
    'resources.category.design-system': 'Design System',
    'resources.category.templates-patterns': 'Templates & Patterns',
    'resources.category.brand-assets': 'Brand & Assets',
    
    // Team
    'team.title': 'Meet Our Design Team',
    'team.subtitle': 'A diverse group of creative minds working together to create exceptional user experiences and drive design excellence.',
    'team.more': 'More →',
    // Team members (fallback to parsed values if key missing)
    'team.member.max.name': 'Max (Maxence Mauduit)',
    'team.member.max.role': 'Experienced Product Designer and CDO',
    'team.member.max.description': 'I lead the creation of playful brand interactions that scale engagement into conversion.',
    'team.member.max.keywords': '0→1 Builder, Systems Thinker, Product Strategist, Design Leader',
    'team.member.jia.name': 'Jia (Sophie Cui)',
    'team.member.jia.role': 'Principal Product Designer',
    'team.member.jia.description': 'Overseeing Buzzvil\'s publisher-side products. Main focus includes revenue-generation and engagement.',
    'team.member.jia.keywords': 'unconventional methods, goal-oriented, trend-hunter',
    'team.member.elle.name': 'Elle (신성욱)',
    'team.member.elle.role': 'Product Designer',
    'team.member.elle.description': 'Designs business-critical user experiences and leads the Ads Self-Serve domain.',
    'team.member.elle.keywords': 'Efficient Operations, Simplified Complexity',
    'team.member.joy.name': 'Joy (배희준)',
    'team.member.joy.role': 'Product Designer',
    'team.member.joy.description': 'Designs engagement-driven ad products that connect publishers and ad agencies, creating playful experiences with monetization in mind.',
    'team.member.joy.keywords': 'playful experience, interaction design',
    'team.member.rina.name': 'Rina (Erin Lee)',
    'team.member.rina.role': 'Product Designer',
    'team.member.rina.description': 'Design and oversee the UI/UX for publisher-side products and the internal tool used to control, monitor, and support them.',
    'team.member.rina.keywords': 'UI/UX, Usability Improvement, System Design, logical thinking',
    'team.member.mido.name': 'Mido (정초원)',
    'team.member.mido.role': 'Product Design intern',
    'team.member.mido.description': 'Product designer on the AD Product Team, designing the user experience for our game user-acquisition product.',
    'team.member.mido.keywords': 'Product Design, Interaction Design, UX/UI',
    
    // Tools
    'tools.title': 'Our Stack',
    'tools.subtitle': 'The tools that power our design work.',
    'tools.visit': 'Visit Tool',
    'tools.category.design-development': 'Design & Development Tools',
    'tools.tool.figma.name': 'Figma Suite (org)',
    'tools.tool.figma.description': 'Our primary design tool for creating interfaces, prototypes, and design systems with team collaboration',
    'tools.tool.figma.feature.0': 'Design System',
    'tools.tool.figma.feature.1': 'Prototyping',
    'tools.tool.figma.feature.2': 'Team Collaboration',
    'tools.tool.gpt.name': 'GPT Business',
    'tools.tool.gpt.description': 'AI-powered assistant for design ideation, content generation, and workflow optimization',
    'tools.tool.gpt.feature.0': 'AI Assistant',
    'tools.tool.gpt.feature.1': 'Content Generation',
    'tools.tool.gpt.feature.2': 'Workflow Optimization',
    'tools.tool.cursor.name': 'Cursor',
    'tools.tool.cursor.description': 'AI-powered code editor for design system development and frontend implementation',
    'tools.tool.cursor.feature.0': 'AI Coding',
    'tools.tool.cursor.feature.1': 'Design System',
    'tools.tool.cursor.feature.2': 'Frontend Development',
    
            // Brand
            'brand.sections.principles': 'Principles',
            'brand.sections.guidelines': 'Guidelines',
            'brand.sections.resources': 'Resources',
            'brand.intro.catchphrase': 'Shaping how Buzzvil looks, feels, and behaves across every touchpoint.',
            'brand.principles.title': 'Brand Principles',
            'brand.principles.description': 'Our core brand principles that guide every decision, interaction, and experience we create. These fundamental values ensure consistency and authenticity across all touchpoints.',
            'brand.guidelines.title': 'Brand Guidelines',
            'brand.guidelines.description': 'Comprehensive guidelines for applying our brand consistently across all platforms and touchpoints. From logo usage to color palettes, typography, and voice.',
            'brand.resources.title': 'Brand Resources',
            'brand.resources.description': 'Download our brand assets, templates, and resources. Everything you need to implement our brand consistently across your projects and campaigns.',
            
            // Brand guidelines (Identity System 2.0)
            'brand.hero.tag': 'Identity System 26.1',
            'brand.hero.title': 'Expressive in Motion. Iconic in Context.',
            'brand.hero.description': 'Guided by product behavior, our brand comes to life through interaction, allowing its form, motion, and identity to adapt without losing its essence.',
            'brand.hero.cta': 'Explore Guidelines',
            'brand.nav.logo': 'Logo',
            'brand.nav.colors': 'Colors',
            'brand.nav.typography': 'Typography',
            'brand.nav.imagery': 'Imagery',
            'brand.nav.downloads': 'Downloads',
            'brand.logo.title': 'The Chameleon',
            'brand.logo.description': 'The logo is chameleon-like. It adapts to its environment, taking on black or white depending on the background. While it can take on primary or secondary colors in specific partner contexts, we default to the monochrome usage to maintain our clean brand aesthetic.',
            'brand.logo.lightBg': 'On Light Background',
            'brand.logo.darkBg': 'On Dark Background',
            'brand.logo.partnerContext': 'Partner Context Examples',
            'brand.logo.kakaoBank': 'KakaoBank',
            'brand.logo.kBank': 'K Bank',
            'brand.logo.oliveYoung': 'Olive Young',
            'brand.logo.clearspace': 'Clearspace',
            'brand.logo.clearspaceDesc': 'Always maintain generous clearspace around the logo to ensure legibility and impact.',
            'brand.logo.unacceptable': 'Unacceptable Usage',
            'brand.logo.unacceptableDesc': 'To maintain brand integrity, avoid manipulating the logo in ways that compromise its legibility or form.',
            'brand.logo.noStretch': 'Do not stretch',
            'brand.logo.noCrop': 'Do not crop',
            'brand.logo.noRotate': 'Do not rotate',
            'brand.logo.noDeform': 'Do not deform',
            'brand.logo.logoTreatment': 'Logo Treatment',
            'brand.logo.maskingTitle': 'Masking (Image & Video)',
            'brand.logo.maskingDesc': 'As part of our chameleon philosophy, we allow image, illustration, or video injection inside our logo shape. Ensure sufficient contrast with the background.',
            'brand.logo.threeDTitle': '3D Guidelines',
            'brand.logo.threeDDesc': 'We allow isometric 3D transformations to add depth. The aesthetic must remain abstract, simple, and tonal. Avoid free-form 3D distortion.',
            'brand.logo.isometricLabel': 'Isometric (Allowed)',
            'brand.logo.freeformLabel': 'Free-form 3D (Not Allowed)',
            'brand.colors.grayscale': 'Grayscale',
            'brand.colors.grayscaleDesc': 'Our primary palette. We aim for a high-contrast, clean look using almost exclusively black and white tones.',
            'brand.colors.red': 'Accent Red',
            'brand.colors.redDesc': 'Used sparingly for primary actions or critical alerts. Aim for <10% usage in any composition.',
            'brand.colors.orange': 'Accent Orange',
            'brand.colors.orangeDesc': 'Secondary accent color, complements the red. Use for banners or highlights.',
            'brand.colors.copied': 'Copied!',
            'brand.typography.primaryTitle': 'Primary: Pretendard / Inter',
            'brand.typography.primaryDesc': 'Pretendard for Korean, Inter for Latin. Our main typeface for its cleanliness, readability, and modern aesthetic. Works well in both headings and body text.',
            'brand.typography.h1Meta': 'Heading 1 / Bold / 48px',
            'brand.typography.h1Text': 'Ads That Work',
            'brand.typography.h2Meta': 'Heading 2 / Semibold / 36px',
            'brand.typography.h2Text': 'Where user benefit meets advertiser success',
            'brand.typography.bodyMeta': 'Body / Regular / 16px',
            'brand.typography.bodyText': 'Our logo is a chameleon. It can take any color from our customer/partners. By default and in the context of our brand, it takes the black or white depending on background.',
            'brand.typography.heroTitle': 'Display: Nunito (EN only)',
            'brand.typography.heroDesc': 'English-only typeface for navigation, hero headlines, and high-impact display text. Rounded and approachable, it adds warmth to key touchpoints.',
            'brand.typography.heroMeta': 'Header / Extrabold / 36px',
            'brand.typography.secondaryTitle': 'Secondary: Nanum Gothic Coding / Anonymous Pro',
            'brand.typography.secondaryDesc': 'Monospace typefaces that signal precision, accuracy, and a data-centric mindset. Rooted in our tech-first DNA, they reinforce the trust our partners place in our numbers. Use for kickers, labels, metrics, code snippets, or technical data.',
            'brand.typography.kickerMeta': 'Kicker / Bold / 14px',
            'brand.typography.kickerText': 'Product Backend Team',
            'brand.typography.dataMeta': 'Data / Regular / 14px',
            'brand.imagery.title': 'Imagery Guidelines',
            'brand.imagery.description': 'Our brand is built to move. Static imagery is a last resort. When we do use it, every pixel must be real, purposeful, and unmistakably ours.',
            'brand.imagery.vectorTitle': 'Vector & Lottie First',
            'brand.imagery.vectorDesc': 'SVG, vector artwork, and Lottie animations are our default. Clean, scalable, and brand-native. Used for illustrations, icons, diagrams, motion assets, and any visual that supports our design system.',
            'brand.imagery.productTitle': 'Product Screenshots',
            'brand.imagery.productDesc': 'Pixel images earn their place when showing real products. Actual screenshots, flows, and interfaces, not mockups. Trust comes from showing what we truly build.',
            'brand.imagery.teamTitle': 'Our People & Space',
            'brand.imagery.teamDesc': 'Real photos of our office and members. Candid, unstaged, authentic. No stock photography. No getty images. Ever.',
            'brand.imagery.motionTitle': 'Motion Over Stills',
            'brand.imagery.motionDesc': 'Vector, Lottie, and code-driven visuals come first. Photos and screenshots earn their place only when they show something real. Our actual product, our actual people, our actual space.',
            'brand.imagery.bullet1': 'Vector, Lottie, and code-driven visuals come first.',
            'brand.imagery.bullet2': 'Photos and screenshots earn their place only when they show something real. Our actual product, our actual people, our actual space.',
            'brand.downloads.logoGenerator': 'Logo Generator',
            'brand.downloads.logoGeneratorDesc': 'Customize and download the official brand assets. Select the type, choose a color, and get a high-resolution PNG.',
            'brand.downloads.iconGenerator': 'Icon Generator',
            'brand.downloads.iconGeneratorDesc': 'Search and generate consistent iconography. Optimized for reward, points, and game-related interfaces.',
            'brand.downloads.isometricGenerator': 'Isometric Generator',
            'brand.downloads.isometricGeneratorDesc': 'Generate a 3D isometric version of the logo mark. Adjust the angle and perspective to fit your composition.',
            'brand.downloads.comingSoon': 'Coming soon',
            'brand.logoGenerator.title': 'Logo Generator',
            'brand.logoGenerator.description': 'Customize and download the official brand assets. Select the type, choose a color, and get a high-resolution PNG.',
            'brand.logoGenerator.assetType': 'Asset Type',
            'brand.logoGenerator.mark': 'Logo Mark',
            'brand.logoGenerator.wordmark': 'Wordmark',
            'brand.logoGenerator.color': 'Color',
            'brand.logoGenerator.customHex': 'Custom Hex',
            'brand.logoGenerator.download': 'Download PNG (512px Height)',
            'brand.iconGenerator.title': 'Icon Generator',
            'brand.iconGenerator.description': 'Search and generate consistent iconography. Optimized for reward, points, and game-related interfaces.',
            'brand.iconGenerator.searchLabel': 'Search Library',
            'brand.iconGenerator.searchPlaceholder': 'Search icons (e.g. Calendar, User, Gift...)',
            'brand.iconGenerator.results': 'Results',
            'brand.iconGenerator.popular': 'Popular Icons',
            'brand.iconGenerator.noResults': 'No icons found for "{query}"',
            'brand.iconGenerator.loadMore': 'Load More',
            'brand.iconGenerator.weight': 'Weight',
            'brand.iconGenerator.color': 'Color',
            'brand.iconGenerator.customHex': 'Custom Hex',
            'brand.iconGenerator.download': 'Download PNG',
            'brand.iconGenerator.preview': 'Preview',
            'brand.isometricGenerator.title': 'Isometric Projection',
            'brand.isometricGenerator.description': 'Generate an orthographic isometric projection of the logo mark. Outputs remain brand-safe, repeatable, and legible at small sizes.',
            'brand.isometricGenerator.angle': 'Angle',
            'brand.isometricGenerator.direction': 'Direction',
            'brand.isometricGenerator.download': 'Download PNG (512px)',
            'brand.isometricGenerator.angleSubtle': 'Subtle',
            'brand.isometricGenerator.angleStandard': 'Standard',
            'brand.isometricGenerator.angleStrong': 'Strong',
            'brand.isometricGenerator.dirLeft': 'Left',
            'brand.isometricGenerator.dirCenter': 'Center',
            'brand.isometricGenerator.dirRight': 'Right',
            'brand.isometricGenerator.color': 'Color',
            'brand.isometricGenerator.customHex': 'Custom',
            'brand.isometricGenerator.dirTopRight': 'Top-right',
            'brand.isometricGenerator.dirTopLeft': 'Top-left',
            'brand.isometricGenerator.dirBottomRight': 'Bottom-right',
            'brand.isometricGenerator.dirBottomLeft': 'Bottom-left',
            'brand.isometricGenerator.depth': 'Depth',
            'brand.isometricGenerator.depthHint': 'Controls the dimensional offset of the mark.',
            'brand.isometricGenerator.edgeStyle': 'Edge Style',
            'brand.isometricGenerator.edgeSharp': 'Sharp',
            'brand.isometricGenerator.edgeSoft': 'Soft',
            'brand.isometricGenerator.edgeOutline': 'Outline only',
            'brand.isometricGenerator.faceColor': 'Face Color Mode',
            'brand.isometricGenerator.faceFlat': 'Flat',
            'brand.isometricGenerator.faceSubtle': 'Subtle shade',
            'brand.isometricGenerator.faceStroke': 'Stroke-only',
            'brand.isometricGenerator.brandSafe': 'Brand-safe',
            
            // Product
            'product.hero.tag': 'Product Design System',
            'product.hero.title': 'Simple. Iconic.\nDelightful.',
            'product.hero.description': 'Every interaction is purposeful, every surface trustworthy. We design experiences that earn attention and reward it.',
            'product.hero.cta': 'Explore Principles',
            'product.sections.principles': 'Principles',
            'product.sections.patterns': 'Patterns',
            'product.sections.conventions': 'Conventions',
            'product.sections.resources': 'Resources',
            'product.intro.catchphrase': 'Designing delightful experiences that users love to engage with.',

            // Interaction Layers
            'product.layers.title': 'Interaction Layers',
            'product.layers.subtitle': 'Every feature is built from two distinct layers that work together to create cohesive, memorable experiences.',
            'product.layers.phase1.title': 'This is a Feature',
            'product.layers.phase1.subtitle': 'An Engagement feature, a Mission flow, a Reward feedback',
            'product.layers.phase2.delivery': 'A feature is almost always made of a Delivery UX layer.',
            'product.layers.phase2.deliveryEn': 'Grids, navigation, loading states, transitions',
            'product.layers.phase2.signature': 'And a Signature UX layer',
            'product.layers.phase2.signatureEn': 'Gamification, moments, iconic interactions',
            'product.layers.delivery.title': 'The Delivery Layer',
            'product.layers.delivery.label': 'Simple, familiar & trustful',
            'product.layers.delivery.bullet1': 'Navigation, layout, containers, grids, loading states, transitions',
            'product.layers.delivery.bullet2': 'Consistency across very different Signature experiences',
            'product.layers.delivery.bullet3': 'Packaging, theming, structure',
            'product.layers.delivery.bullet4': 'Built for speed, reliability, and reuse',
            'product.layers.signature.title': 'The Signature Layer',
            'product.layers.signature.label': 'Iconic & delightful',
            'product.layers.signature.bullet1': 'Iconic, high-engagement interactions',
            'product.layers.signature.bullet2': 'Differentiating mechanics (gamification, missions, moments)',
            'product.layers.signature.bullet3': 'Where creativity and experimentation live',
            'product.layers.signature.bullet4': 'Not composed from reusable blocks',
            'product.sections.layers': 'Composition',
            'product.sections.chameleon': 'Variables',

            'product.chameleon.title': 'Variables',
            'product.chameleon.description': 'Our products serve hundreds of partners, each with their own brand. Chameleon is our token-driven theming strategy: a single, structured set of design tokens that powers every surface. Colors, spacing, radii, shadows, typography. Fully customizable, always consistent.',
            'product.chameleon.presets': 'Theme presets',
            'product.chameleon.grabLabel': 'Grab from URL',
            'product.chameleon.tokens': 'Token set',
            'product.chameleon.preview': 'Live preview',

            // Patterns
            'product.patterns.title': 'Patterns',
            'product.patterns.description': 'A unified library of interaction and visual patterns that define how every Buzzvil product looks and behaves. Rather than separating UX from visual, we treat them as one interconnected system. Everything lives in a single, browsable library.',
            'product.patterns.library': 'Buzzvil Pattern Library',
            'product.patterns.libraryDesc': 'The complete, browsable pattern library is maintained internally. Access is restricted to Buzzvil team members.',
            'product.patterns.comingSoon': 'Coming soon',

            'product.patterns.interaction.title': 'Interaction Patterns',
            'product.patterns.interaction.intro': 'Before any screen is drawn, we define how it behaves. Interaction patterns are the behavioral skeleton of every product surface. They govern how a user enters a flow, what happens while content loads, how feedback is delivered, and the physics behind every transition. This category also covers micro-interactions: the small, often invisible details (an icon that breathes, a counter that springs, a swipe that snaps) that compound into the feeling of a polished product. When these patterns are consistent, users stop noticing them. That is the goal.',

            'product.patterns.uikit.title': 'UI Kit',
            'product.patterns.uikit.intro': 'The UI Kit is where interaction patterns become tangible. Every component exists to serve a specific behavioral purpose defined upstream. Atoms are the smallest units: a button knows how to communicate loading, disabled, and success states. Modules compose atoms into self-contained pieces like a campaign card or a reward row. Views orchestrate modules into full screens. The kit is built for Chameleon theming from the ground up. Every component accepts token overrides, responds to breakpoints, and adapts to platform conventions without losing structural parity.',

            'product.patterns.visual.title': 'Visual Language',
            'product.patterns.visual.intro': 'Every visual asset we produce is designed to live inside a theming system. Icons, illustrations, and decorative elements are built with color structures that automatically adapt when a publisher\'s brand is applied. The same gift box rendered in four different palettes, each feeling native to its context. Typography, hierarchy, and imagery follow the same principle: parametric by default, so that visual consistency across hundreds of partner brands is a given, not an effort.',

            // Conventions
            'product.conventions.title': 'Conventions',
            'product.conventions.description': 'The shared rituals, processes, and standards that keep our design system healthy and our teams aligned. These are not guidelines to interpret; they are agreements to follow.',
            'product.conventions.workflow.title': 'Design Workflow',
            'product.conventions.workflow.desc': 'Every feature follows a structured path from exploration to production. The workflow integrates design review and handoff as formal checkpoints rather than afterthoughts.',
            'product.conventions.workflow.bulletCount': '6',
            'product.conventions.workflow.bullet1': 'Discovery: problem framing, competitive audit, and user research synthesis.',
            'product.conventions.workflow.bullet2': 'Wireframe: low-fidelity flows validated with product and engineering before any visual work begins.',
            'product.conventions.workflow.bullet3': 'Visual design: high-fidelity screens built from the pattern library, using real tokens and components.',
            'product.conventions.workflow.bullet4': 'Design review: weekly team critique and bi-weekly cross-team review. Changes to shared patterns require consensus from design leads.',
            'product.conventions.workflow.bullet5': 'Handoff: annotated specs with token references, redlines, and interactive prototypes delivered in Figma. A handoff meeting is held before every sprint.',
            'product.conventions.workflow.bullet6': 'QA: design-side visual QA on staging before release. Pixel-level checks against the spec.',
            'product.conventions.tokens.title': 'Token Governance',
            'product.conventions.tokens.desc': 'Design tokens are the single source of truth connecting design and code. Their integrity is critical, so additions, modifications, and removals follow a formal process.',
            'product.conventions.tokens.bulletCount': '5',
            'product.conventions.tokens.bullet1': 'All tokens live in a versioned JSON file synced between Figma and the codebase.',
            'product.conventions.tokens.bullet2': 'New tokens require a proposal (name, value, rationale) reviewed by the design system team.',
            'product.conventions.tokens.bullet3': 'Breaking changes (rename, removal, value shift) enter a deprecation window of at least one release cycle.',
            'product.conventions.tokens.bullet4': 'Alias tokens (e.g. {theme/primary}) are preferred over raw values. Components should never hardcode hex or px.',
            'product.conventions.tokens.bullet5': 'Token audits run quarterly to identify unused, duplicate, or inconsistent entries.',
            'product.conventions.naming.title': 'Naming Conventions',
            'product.conventions.naming.desc': 'Consistent naming reduces cognitive load and makes the system searchable, scriptable, and predictable. Every artifact in the system follows the same rules.',
            'product.conventions.naming.bulletCount': '5',
            'product.conventions.naming.bullet1': 'Tokens: kebab-case, semantic over visual. Use "primary" not "blue", "base-content" not "dark-text".',
            'product.conventions.naming.bullet2': 'Figma layers: kebab-case matching the component or token name. No "Frame 47" or "Group 12".',
            'product.conventions.naming.bullet3': 'Components: PascalCase in code, kebab-case in Figma. Name describes purpose, not appearance (e.g. RewardBadge, not RedCircle).',
            'product.conventions.naming.bullet4': 'Files & branches: feature/[scope]-[description] for branches, kebab-case for design files (e.g. mission-flow-v2.fig).',
            'product.conventions.naming.bullet5': 'Icons: [category]/[name]-[size] (e.g. navigation/arrow-left-24). Always include the grid size in the name.',
            'product.conventions.versioning.title': 'Versioning & Changelog',
            'product.conventions.versioning.desc': 'Every release of the design system is semantically versioned so that consumers know exactly what changed and whether they need to act.',
            'product.conventions.versioning.bulletCount': '5',
            'product.conventions.versioning.bullet1': 'Semantic versioning: MAJOR for breaking changes, MINOR for new tokens/components, PATCH for bug fixes and refinements.',
            'product.conventions.versioning.bullet2': 'A public changelog accompanies every release, listing additions, modifications, deprecations, and removals.',
            'product.conventions.versioning.bullet3': 'Figma library versions are tagged with the same version number as the code package for traceability.',
            'product.conventions.versioning.bullet4': 'Deprecation notices are published at least one minor version before removal, with migration guidance.',
            'product.conventions.versioning.bullet5': 'Release cadence: minor releases every two weeks aligned with sprint boundaries; patches as needed.',

            'product.principles.alignmentQuestionLabel': 'Alignment question',
            'product.principles.simple.shortTitle': 'Simple',
            'product.principles.simple.title': 'Simple',
            'product.principles.simple.description': 'Designs must be immediately understandable. When there are two ways to do something, choose the simpler one. Users should never need prior knowledge, hidden tricks, or obsessive attention to navigate. Simple means clean, accessible, and predictable. Even with rich interactions or multi-mission flows, the path must stay obvious.',
            'product.principles.simple.alignmentQuestion': 'Could my grandma use this without help?',
            'product.principles.iconic.shortTitle': 'Iconic',
            'product.principles.iconic.title': 'Iconic',
            'product.principles.iconic.description': 'Our work should be distinctive, high-quality, and instantly recognizable. We aim for designs that feel modern, confident, and relevant to our core audience—designs that make other designers quietly jealous. If a screen looks like it could belong to any competitor, it is not finished.',
            'product.principles.iconic.alignmentQuestion': 'Is this something people would share or reference?',
            'product.principles.delightful.shortTitle': 'Delightful',
            'product.principles.delightful.title': 'Delightful',
            'product.principles.delightful.description': 'Interactions should feel enjoyable, not mechanical. Delight is not decoration. It is well-timed motion, playful feedback, and micro-moments that make users feel rewarded and engaged. It must never get in the way of speed or clarity.',
            'product.principles.delightful.alignmentQuestion': 'Is this genuinely fun and engaging?',
            'product.principles.purposeful.shortTitle': 'Purposeful',
            'product.principles.purposeful.title': 'Purposeful',
            'product.principles.purposeful.description': 'Every experience must deliver clear, meaningful value. Time and effort spent by users must be worth it. We operate in a reward-driven ecosystem. Value must be obvious, immediate, and fair. If a flow feels like work, the reward does not justify it, or the benefit is not visible enough, we are wasting everyone\'s time.',
            'product.principles.purposeful.alignmentQuestion': 'Is this worth the user\'s time, or are we just manufacturing effort for no reason?',
            'product.principles.trustworthy.shortTitle': 'Trustworthy',
            'product.principles.trustworthy.title': 'Trustworthy',
            'product.principles.trustworthy.description': 'Users should always feel safe, oriented, and confident, even as they move across funnels. Our experiences span app surfaces, web, and hybrid transitions. The design must stay unified and reliable so users never wonder if they have been dropped into a sketchy third-party zone. Trust comes from consistency, smoothness, tone, and predictable behavior.',
            'product.principles.trustworthy.alignmentQuestion': 'Would a normal user trust this flow from start to finish, or does it feel like we teleported them into a different product?',

            // New submenu items
            'nav.product.uxPatterns': 'UX Patterns',
            'nav.product.visualPatterns': 'Visual Patterns',
            'nav.product.workflowRituals': 'Workflow & Rituals',
            
            // Page-specific translations
            'pages.backToGuidelines': 'Back to Guidelines',
            'pages.sections.interactionPatterns': 'Interaction Patterns',
            'pages.sections.uiKit': 'UI Kit',
            'pages.sections.microInteractions': 'Micro-interactions',
            'pages.sections.designPrinciples': 'Design Principles',
            'pages.sections.visualGuidelines': 'Visual Guidelines',
            'pages.sections.comingSoon': 'Coming Soon',
            'pages.sections.corePrinciples': 'Core Principles',
            'pages.sections.workflowSteps': 'Workflow Steps',
            
            // Interaction Patterns specific
            'interactionPatterns.whileLoading': 'While loading',
            'interactionPatterns.whileLoading.description': 'Skeleton screens, loading states, and progressive disclosure patterns that keep users engaged during wait times.',
            'interactionPatterns.pageScroll': 'Page Scroll',
            'interactionPatterns.pageScroll.description': 'Default vertical scrolling as the primary interaction pattern, with parallax and reveal animations.',
            'interactionPatterns.notify': 'Notify',
            'interactionPatterns.notify.description': 'Toast notifications, banners, and system messages that provide feedback without interrupting user flow.',
            'interactionPatterns.alert': 'Alert',
            'interactionPatterns.alert.description': 'Critical notifications and warnings that require immediate user attention and action.',
            'interactionPatterns.pauseAsk': 'Pause & Ask',
            'interactionPatterns.pauseAsk.description': 'Modal dialogs and popups that pause user flow to gather information or confirm actions.',
            'interactionPatterns.magnify': 'Magnify',
            'interactionPatterns.magnify.description': 'Expandable content and bottom sheets that reveal additional information or options.',
            'interactionPatterns.screenToScreen': 'Screen to Screen',
            'interactionPatterns.screenToScreen.description': 'Smooth transitions between different views or screens with clear navigation hierarchy.',
            'interactionPatterns.feedback': 'Feedback',
            'interactionPatterns.feedback.description': 'Immediate visual or haptic feedback for user interactions to create responsive experiences.',
            'interactionPatterns.moreToCome': 'More to come',
            'interactionPatterns.moreToCome.description': 'Additional patterns will be added as we discover and document new interaction needs.',
            
            // UI Kit specific
            'uiKit.atoms': 'Atoms',
            'uiKit.molecules': 'Molecules',
            'uiKit.organisms': 'Organisms',
            'uiKit.templates': 'Templates',
            'uiKit.pages': 'Pages',
            'uiKit.moreToCome': 'More to come',
            
            // Micro-interactions specific
            'microInteractions.livingIcons': 'Living Icons',
            'microInteractions.emphasisOn': 'Emphasis On',
            'microInteractions.rewardDelights': 'Reward Delights',
            'microInteractions.moreToCome': 'More to come',
            
            // Code preview
            'codePreview.title': 'Code Example',
            'codePreview.copy': 'Copy',
            'codePreview.copied': 'Copied!',
            
            // Live preview
            'livePreview.title': 'Live Preview',
            'livePreview.comingSoon': 'Preview coming soon',
            
            // Footer
            'footer.description': 'Home to Buzzvil\'s design source of truth. We build in the open. This portal is primarily meant to be used internally and by our partners, but we also like anyone to have a look at how we work!',
            'footer.foundations.mission': 'The Mission',
            'footer.foundations.philosophy': 'Our Mindset',
            'footer.foundations.values': 'Working Principles',
            'footer.foundations.team': 'Our Team',
            'footer.foundations.tools': 'Our Stack',
            'footer.brand.principles': 'Principles',
            'footer.brand.guidelines': 'Guidelines',
            'footer.brand.resources': 'Resources',
            'footer.product.principles': 'Principles',
            'footer.product.guidelines': 'Guidelines',
            'footer.product.resources': 'Resources',
            'footer.connect.buzzvil': 'Buzzvil',
            'footer.connect.contact': 'Contact',
            'footer.connect.careers': 'Careers',
            'footer.connect.figma': 'Figma',
            'footer.connect.github': 'GitHub',
            'footer.connect.linkedin': 'LinkedIn',
            'footer.made': 'Made with',
            'footer.by': 'by the Buzzvil Design Team',
            'footer.privacy': 'Privacy Policy',
            'footer.terms': 'Terms of Service',
            'footer.about': 'About This Site',

            // About page
            'about.kicker': 'About this site',
            'about.title': 'How This Site Was Built',
            'about.description': 'Design Buzzvil is Buzzvil\'s living design portal. It documents our brand, product principles, and design system in a bilingual, fully animated, statically exported website. Here\'s a look under the hood.',
            'about.contributors': 'Contributors',
            'about.contributorNote': 'Sole author and maintainer. Future collaborators welcome.',
            'about.techStack': 'Tech Stack',
            'about.architecture': 'Architecture & Logic',
            'about.viewSource': 'View Source on GitHub',
  },
  ko: {
    // Navigation
    'nav.foundations': '기반',
    'nav.brand': '브랜드',
    'nav.product': '제품',
    'nav.team': '팀',
    'nav.tools': '도구',
    'nav.sections.mission': '미션',
    'nav.sections.philosophy': '마인드셋',
    'nav.sections.values': '작업 원칙',
    'nav.sections.team': '우리의 팀',
    'nav.sections.tools': '우리의 스택',
    
    // Contact Banner
    'banner.title': '커피 한 잔 하며 만나볼까요?',
    'banner.cta': '미팅 예약하기',
    'banner.cta.short': '연락',
    'banner.requirements.schedule': '시간 예약',
    'banner.requirements.info': '정보 포함',
    
    // Hero
    'hero.title': 'Buzzvil Design',
    'hero.subtitle': '매력적인. 재미있는. 확장 가능한.',
    'hero.sentence.start': '우리는 구축합니다',
    'hero.sentence.end': '경험을.',
    'hero.keyword.engaging': '매력적인',
    'hero.keyword.playful': '재미있는',
    'hero.keyword.scalable': '확장 가능한',
            'hero.explore': '기반 탐색',
            'hero.brand': '브랜드',
            'hero.product': '제품',
            'hero.scroll': '스크롤하여 탐색',
    
            // Mission & Vision
            'mission.title': '미션 & 비전',
            'mission.subtitle': '버즈빌에서 우리가 하는 모든 일을 이끄는 미션과 비전.',
            'mission.mission.title': '미션',
            'mission.mission.subtitle': '지금 우리가 하는 일',
            'mission.mission.content': '우리는 사람들이 버즈빌의 광고 캠페인과 브랜드를 발견하고, 경험하고, 지속적으로 참여하는 방식을 형성하는 의미 있는 상호작용을 디자인합니다. 우리의 작업은 광고를 사람들이 탐험하고 싶어하는 경험으로 바꾸며, 주의를 끌고, 호기심을 자극하며, 광고주에게 성과를 가져다주는 순간들을 만듭니다.',
            'mission.vision.title': '비전',
            'mission.vision.subtitle': '우리가 구축하는 미래',
            'mission.vision.content': '우리는 광고 캠페인과 브랜드 경험을 사용자와 광고주를 연결하는 매력적이고 반복 가능한 상호작용으로 변화시켜 AdTech 디자인의 새로운 표준을 제시합니다. 이러한 새로운 참여 방식을 통해, 버즈빌은 광고가 즐겁고, 사람들의 일상 경험에 자연스럽게 통합되는 미래를 이끕니다.',
    
            // Philosophy
            'philosophy.title': '철학',
            'philosophy.subtitle': '우리가 접근하는 방식',
            'philosophy.content': '버즈빌에서 디자인은 사람들이 광고를 경험하는 방식을 형성합니다. 방해가 아닌 즐거운 연결의 순간으로 말입니다. 우리는 브랜드 접점부터 제품 내 경험까지 모든 상호작용이 재미있고, 매력적이며, 자연스러워야 한다고 믿습니다. 우리의 역할은 버즈빌이 생태계 전반에서 어떻게 보이고, 느껴지고, 행동하는지를 통합하여 캠페인과 플랫폼을 하나의 일관되고 즐거운 경험으로 만드는 것입니다. 우리의 원칙과 원팀 정신에 이끌려, 우리는 신뢰를 영감하고, 성과를 추진하며, AdTech가 될 수 있는 새로운 표준을 설정하기 위해 디자인합니다.',
    
            // Ways of Working
            'waysOfWorking.title': '작업 방식',
            'waysOfWorking.subtitle': '버즈빌 디자인에서 우리가 생각하고, 창조하고, 협업하는 방식.',
            'waysOfWorking.principles.title': '우리의 원칙',
            'waysOfWorking.principles.subtitle': '버즈빌에서 디자인하기 위해 함께 작업하는 방식.',
            'waysOfWorking.team.title': '우리의 팀',
            'waysOfWorking.team.subtitle': '버즈빌 디자인을 만드는 사람들.',
            'waysOfWorking.stack.title': '우리의 스택',
            'waysOfWorking.stack.subtitle': '우리의 디자인 작업을 지원하는 도구들.',
    
    // Principles
    'principles.title': '원칙',
    'principles.subtitle': '디자인과 개발 접근 방식을 이끄는 원칙들.',
    'principles.reward.title': '보상 = 시간',
    'principles.reward.shortTitle': '보상',
    'principles.reward.content': '보상은 사용자 주의의 투명하고 측정 가능한 교환입니다. 메커니즘: 1P ≈ 1초의 주의. 이는 사용자에게 일관성을, 광고주에게 예측 가능성을 제공합니다.',
    'principles.delight.title': '기만 없는 기쁨',
    'principles.delight.shortTitle': '기쁨',
    'principles.delight.content': '보상은 동기를 불러일으키지만, 경험이 참여를 지속시킵니다. 우리는 절대 다크 패턴을 사용하지 않습니다: 광고를 다른 광고 위에 겹치지 않고, 오해를 불러일으키지 않으며, 함정에 빠뜨리지 않습니다. 상호작용은 재미있고 명확하며 존중스러워야 합니다.',
    'principles.scalable.title': '디자인으로 확장 가능하게',
    'principles.scalable.shortTitle': '확장성',
    'principles.scalable.content': '모든 디자인 결정은 제품, 파트너, 비즈니스 모델에 걸쳐 확장되어야 합니다. 우리는 의미 있는 맞춤화를 제공하지만 지속 불가능한 예외는 피합니다. 이러한 원칙은 시스템을 분할하는 비즈니스나 제품 결정을 거부할 수 있습니다.',
    
    // Principles Characteristics
    'principles.reward.characteristics.0': '투명한 교환',
    'principles.reward.characteristics.1': '측정 가능한 주의',
    'principles.reward.characteristics.2': '사용자 일관성',
    'principles.reward.characteristics.3': '광고주 예측 가능성',
    'principles.delight.characteristics.0': '다크 패턴 없음',
    'principles.delight.characteristics.1': '재미있는 상호작용',
    'principles.delight.characteristics.2': '명확한 소통',
    'principles.delight.characteristics.3': '존중스러운 디자인',
    'principles.scalable.characteristics.0': '크로스 제품 확장',
    'principles.scalable.characteristics.1': '의미 있는 맞춤화',
    'principles.scalable.characteristics.2': '시스템 무결성',
    'principles.scalable.characteristics.3': '결정 거부 권한',
    
    // Values
    'values.title': '작업 원칙',
    'values.subtitle': '버즈빌에서 디자인하기 위해 함께 작업하는 방식.',
    'values.build.title': '열린 공간에서 구축',
    'values.build.shortTitle': '열린 공간에서 구축',
    'values.build.content': '우리는 거칠게 시작하고, 일찍 공유하며, 빠르게 반복합니다. 모든 디자이너는 탐색을 가속화하는 AI 도구에 접근할 수 있습니다. 피드백과 빠른 루프는 아이디어를 견고하고 프로덕션 준비된 솔루션으로 정제하는 데 도움이 됩니다.',
    'values.build.tagline': '빠르게 반복하라.',
    'values.clarity.title': '피드백을 통한 명확성',
    'values.clarity.shortTitle': '명확하게',
    'values.clarity.content': '우리는 솔직하고 정확하게 소통합니다. 피드백은 우리가 성장하는 방법입니다: 명확하게 주고, 열린 마음으로 받고, 건설적으로 적용합니다. 명확한 소통은 신뢰를 구축하고 낭비된 노력을 피합니다.',
    'values.clarity.tagline': '명확성을 먼저, 피드백은 항상.',
    'values.grit.title': '소유하고, 출시하라',
    'values.grit.shortTitle': '소유하고, 출시하라',
    'values.grit.content': '디자이너는 단순히 초안에서 멈추지 않습니다. 우리는 사용자 스토리와 프로젝트의 소유권을 가지고, 첫 스케치부터 프로덕션까지 밀어붙입니다. 우리는 결과가 실제가 될 때까지 끈기와 기술로 이끕니다.',
    'values.grit.tagline': '그릿.',
    'values.explore.title': '대담한 탐험가',
    'values.explore.shortTitle': '탐험가',
    'values.explore.content': '우리는 연구, 실험, AI 채택을 우리 기술의 핵심으로 받아들입니다. 강력한 도구와 탐구 문화를 가지고, 넓게 탐색하고, 엄격하게 검증하고, 자신감 있게 디자인하지 않을 변명이 없습니다.',
    'values.explore.tagline': '대담하게 탐험하고, 깊이 연구하라.',
    'values.team.title': 'One-UX',
    'values.team.shortTitle': 'One-UX',
    'values.team.content': '우리는 확장하기 전에 디자인 팀으로 정렬합니다. 이는 자주 동기화하고, 관례를 공유하고, 일관된 관행을 적용하는 것을 의미합니다. 우리의 정렬은 파트너, 사용자, 광고주가 버즈빌 디자인을 하나의 일관된 시스템으로 경험하도록 보장합니다.',
    'values.team.tagline': '먼저 정렬하고, 함께 확장하라.',
    
    // Values Characteristics
    'values.build.characteristics.0': '빠른 프로토타이핑',
    'values.build.characteristics.1': 'AI 기반 탐색',
    'values.build.characteristics.2': '조기 공유',
    'values.build.characteristics.3': '빠른 반복',
    'values.clarity.characteristics.0': '솔직함과 정확성',
    'values.clarity.characteristics.1': '열린 소통',
    'values.clarity.characteristics.2': '건설적 성장',
    'values.clarity.characteristics.3': '신뢰 구축',
    'values.grit.characteristics.0': '완전한 소유권',
    'values.grit.characteristics.1': '끝까지 배송',
    'values.grit.characteristics.2': '끈기',
    'values.grit.characteristics.3': '프로덕션 집중',
    'values.explore.characteristics.0': '연구 중심',
    'values.explore.characteristics.1': 'AI 채택',
    'values.explore.characteristics.2': '넓은 탐색',
    'values.explore.characteristics.3': '엄격한 검증',
    'values.team.characteristics.0': '팀 정렬',
    'values.team.characteristics.1': '공유된 관례',
    'values.team.characteristics.2': '일관된 관행',
    'values.team.characteristics.3': '일관된 시스템',
    
    // Resources
    'resources.title': '디자인 리소스',
    'resources.subtitle': '탁월한 사용자 경험을 만들기 위해 필요한 모든 것. 최신 디자인 파일, 가이드라인, 템플릿을 다운로드하세요.',
    'resources.category.design-system': '디자인 시스템',
    'resources.category.templates-patterns': '템플릿 & 패턴',
    'resources.category.brand-assets': '브랜드 & 자산',
    
    // Team
    'team.title': '우리 디자인 팀을 만나보세요',
    'team.subtitle': '탁월한 사용자 경험을 만들고 디자인 우수성을 추진하기 위해 함께 일하는 다양한 창의적 마음의 그룹.',
    'team.more': '더보기 →',
    'team.member.max.name': 'Max (Maxence Mauduit)',
    'team.member.max.role': '경험 많은 제품 디자이너 & CDO',
    'team.member.max.description': '참여를 전환으로 확장하는 플레이풀한 브랜드 경험을 만듭니다.',
    'team.member.max.keywords': '0→1 구축, 시스템 사고, 제품 전략, 디자인 리더',
    'team.member.jia.name': 'Jia (Sophie Cui)',
    'team.member.jia.role': '수석 제품 디자이너',
    'team.member.jia.description': '버즈빌 퍼블리셔 측 제품을 담당합니다. 수익 창출과 참여에 중점을 둡니다.',
    'team.member.jia.keywords': '비관례적 방법, 목표 지향, 트렌드 헌터',
    'team.member.elle.name': 'Elle (신성욱)',
    'team.member.elle.role': '제품 디자이너',
    'team.member.elle.description': '비즈니스에 핵심적인 사용자 경험을 디자인하고, Ads Self-Serve 도메인을 이끕니다.',
    'team.member.elle.keywords': '효율적 운영, 단순화된 복잡성',
    'team.member.joy.name': 'Joy (배희준)',
    'team.member.joy.role': '제품 디자이너',
    'team.member.joy.description': '퍼블리셔와 광고 에이전시를 연결하는 참여 중심 광고 제품을 디자인하며, 수익화를 염두에 둔 플레이풀한 경험을 만듭니다.',
    'team.member.joy.keywords': '플레이풀한 경험, 인터랙션 디자인',
    'team.member.rina.name': 'Rina (Erin Lee)',
    'team.member.rina.role': '제품 디자이너',
    'team.member.rina.description': '퍼블리셔 측 제품과 이를 제어·모니터링·지원하는 내부 도구의 UI/UX를 디자인하고 총괄합니다.',
    'team.member.rina.keywords': 'UI/UX, 사용성 개선, 시스템 디자인, 논리적 사고',
    'team.member.mido.name': 'Mido (정초원)',
    'team.member.mido.role': '제품 디자인 인턴',
    'team.member.mido.description': 'AD Product 팀 제품 디자이너. 게임 유저 어퀴지션 제품의 사용자 경험을 디자인합니다.',
    'team.member.mido.keywords': '제품 디자인, 인터랙션 디자인, UX/UI',
    
    // Tools
    'tools.title': '우리의 스택',
    'tools.subtitle': '우리의 디자인 작업을 지원하는 도구들.',
    'tools.visit': '도구 방문',
    'tools.category.design-development': '디자인 & 개발 도구',
    'tools.tool.figma.name': 'Figma Suite (org)',
    'tools.tool.figma.description': '인터페이스, 프로토타입, 디자인 시스템을 팀 협업으로 만드는 주요 디자인 도구.',
    'tools.tool.figma.feature.0': '디자인 시스템',
    'tools.tool.figma.feature.1': '프로토타이핑',
    'tools.tool.figma.feature.2': '팀 협업',
    'tools.tool.gpt.name': 'GPT Business',
    'tools.tool.gpt.description': '디자인 아이디어, 콘텐츠 생성, 워크플로우 최적화를 위한 AI 어시스턴트.',
    'tools.tool.gpt.feature.0': 'AI 어시스턴트',
    'tools.tool.gpt.feature.1': '콘텐츠 생성',
    'tools.tool.gpt.feature.2': '워크플로우 최적화',
    'tools.tool.cursor.name': 'Cursor',
    'tools.tool.cursor.description': '디자인 시스템 개발과 프론트엔드 구현을 위한 AI 코드 에디터.',
    'tools.tool.cursor.feature.0': 'AI 코딩',
    'tools.tool.cursor.feature.1': '디자인 시스템',
    'tools.tool.cursor.feature.2': '프론트엔드 개발',
    
            // Brand
            'brand.sections.principles': '원칙',
            'brand.sections.guidelines': '가이드라인',
            'brand.sections.resources': '리소스',
            'brand.intro.catchphrase': '모든 접점에서 버즈빌이 어떻게 보이고, 느껴지고, 행동하는지를 형성합니다.',
            'brand.principles.title': '브랜드 원칙',
            'brand.principles.description': '모든 결정, 상호작용, 우리가 만드는 경험을 이끄는 핵심 브랜드 원칙들. 이러한 근본적인 가치들은 모든 접점에서 일관성과 진정성을 보장합니다.',
            'brand.guidelines.title': '브랜드 가이드라인',
            'brand.guidelines.description': '모든 플랫폼과 접점에서 브랜드를 일관되게 적용하기 위한 포괄적인 가이드라인. 로고 사용법부터 색상 팔레트, 타이포그래피, 톤앤매너까지.',
            'brand.resources.title': '브랜드 리소스',
            'brand.resources.description': '브랜드 자산, 템플릿, 리소스를 다운로드하세요. 프로젝트와 캠페인에서 브랜드를 일관되게 구현하는 데 필요한 모든 것.',
            
            // Brand guidelines (Identity System 2.0)
            'brand.hero.tag': '아이덴티티 시스템 26.1',
            'brand.hero.title': '모션으로 표현하는. 맥락 속에서 상징적인.',
            'brand.hero.description': '제품 행동에 기반하여, 우리 브랜드는 인터랙션을 통해 생명을 얻으며, 본질을 잃지 않으면서 형태, 모션, 아이덴티티를 유연하게 적응시킵니다.',
            'brand.hero.cta': '가이드라인 살펴보기',
            'brand.nav.logo': '로고',
            'brand.nav.colors': '색상',
            'brand.nav.typography': '타이포그래피',
            'brand.nav.imagery': '이미지',
            'brand.nav.downloads': '다운로드',
            'brand.logo.title': '카멜레온 (The Chameleon)',
            'brand.logo.description': '로고는 카멜레온과 같습니다. 배경에 따라 검은색 또는 흰색으로 적응합니다. 파트너 맥락에서 주색상이나 보조 색상을 사용할 수 있지만, 깨끗한 브랜드 미학을 유지하기 위해 흑백 사용을 권장합니다.',
            'brand.logo.lightBg': '밝은 배경',
            'brand.logo.darkBg': '어두운 배경',
            'brand.logo.partnerContext': '파트너 맥락 예시',
            'brand.logo.kakaoBank': '카카오뱅크',
            'brand.logo.kBank': '케이뱅크',
            'brand.logo.oliveYoung': '올리브영',
            'brand.logo.clearspace': '여백 (Clearspace)',
            'brand.logo.clearspaceDesc': '가독성과 임팩트를 위해 항상 로고 주변에 충분한 여백을 유지하세요.',
            'brand.logo.unacceptable': '잘못된 사용 예',
            'brand.logo.unacceptableDesc': '브랜드 일관성을 유지하기 위해, 가독성이나 형태를 훼손하는 변형은 피해주세요.',
            'brand.logo.noStretch': '늘리지 마세요',
            'brand.logo.noCrop': '자르지 마세요',
            'brand.logo.noRotate': '회전하지 마세요',
            'brand.logo.noDeform': '변형하지 마세요',
            'brand.logo.logoTreatment': '로고 트리트먼트',
            'brand.logo.maskingTitle': '마스킹 (이미지 및 비디오)',
            'brand.logo.maskingDesc': '카멜레온 철학의 일환으로, 로고 형태 내부에 이미지, 일러스트레이션 또는 비디오를 삽입하는 것을 허용합니다. 배경과 충분한 대비를 유지하세요.',
            'brand.logo.threeDTitle': '3D 가이드라인',
            'brand.logo.threeDDesc': '깊이감을 더하기 위한 아이소메트릭 3D 변형은 허용됩니다. 미학은 추상적이고 단순하며 톤이 맞아야 합니다. 자유형 3D 왜곡은 피하세요.',
            'brand.logo.isometricLabel': '아이소메트릭 (허용됨)',
            'brand.logo.freeformLabel': '자유형 3D (허용되지 않음)',
            'brand.colors.grayscale': '그레이스케일',
            'brand.colors.grayscaleDesc': '우리의 주 팔레트입니다. 거의 검은색과 흰색만을 사용하여 높은 대비와 깨끗한 룩을 지향합니다.',
            'brand.colors.red': '강조색 레드',
            'brand.colors.redDesc': '주요 동작이나 중요한 알림에 제한적으로 사용하세요. 전체 구성의 10% 미만으로 사용하는 것을 목표로 하세요.',
            'brand.colors.orange': '강조색 오렌지',
            'brand.colors.orangeDesc': '빨간색을 보완하는 보조 강조색입니다. 배너나 하이라이트에 사용하세요.',
            'brand.colors.copied': '복사됨!',
            'brand.typography.primaryTitle': '주요 서체: Pretendard / Inter',
            'brand.typography.primaryDesc': '한국어는 Pretendard, 라틴은 Inter. 깔끔함, 가독성, 현대적인 미학을 위한 주요 서체입니다. 제목과 본문 모두에 적합합니다.',
            'brand.typography.h1Meta': 'Heading 1 / Bold / 48px',
            'brand.typography.h1Text': '효과적인 광고',
            'brand.typography.h2Meta': 'Heading 2 / Semibold / 36px',
            'brand.typography.h2Text': '사용자 혜택과 광고주 성공이 만나는 곳',
            'brand.typography.bodyMeta': 'Body / Regular / 16px',
            'brand.typography.bodyText': '우리의 로고는 카멜레온입니다. 고객이나 파트너의 어떤 색상이든 취할 수 있습니다. 기본적으로는 배경에 따라 흑백을 취합니다.',
            'brand.typography.heroTitle': '디스플레이 서체: Nunito (영문 전용)',
            'brand.typography.heroDesc': '영문 전용 서체. 네비게이션, 히어로 헤드라인, 임팩트 있는 디스플레이 텍스트에 사용합니다. 둥글고 친근한 인상을 줍니다.',
            'brand.typography.heroMeta': '헤더 / Extrabold / 36px',
            'brand.typography.secondaryTitle': '보조 서체: 나눔고딕코딩 / Anonymous Pro',
            'brand.typography.secondaryDesc': '정밀함, 정확성, 데이터 중심 사고를 전달하는 고정폭 서체입니다. 기술 우선 DNA에 뿌리를 두고, 파트너가 우리의 수치에 두는 신뢰를 강화합니다. 키커, 라벨, 지표, 코드 조각 또는 기술 데이터에 사용하세요.',
            'brand.typography.kickerMeta': 'Kicker / Bold / 14px',
            'brand.typography.kickerText': '프로덕트 백엔드 팀',
            'brand.typography.dataMeta': 'Data / Regular / 14px',
            'brand.imagery.title': '이미지 가이드라인',
            'brand.imagery.description': '우리 브랜드는 움직이도록 만들어졌습니다. 정적 이미지는 최후의 수단이며, 사용할 때는 모든 픽셀이 실제적이고 목적 있고 우리다워야 합니다.',
            'brand.imagery.vectorTitle': '벡터 & Lottie 우선',
            'brand.imagery.vectorDesc': 'SVG, 벡터 아트워크, Lottie 애니메이션이 기본입니다. 깔끔하고 확장 가능하며 브랜드에 적합합니다. 일러스트레이션, 아이콘, 다이어그램, 모션 에셋 등 디자인 시스템을 지원하는 모든 비주얼에 사용됩니다.',
            'brand.imagery.productTitle': '제품 스크린샷',
            'brand.imagery.productDesc': '픽셀 이미지는 실제 제품을 보여줄 때 사용됩니다. 실제 스크린샷, 플로우, 인터페이스. 목업이 아닌. 신뢰는 우리가 실제로 만든 것을 보여주는 데서 옵니다.',
            'brand.imagery.teamTitle': '우리의 사람들과 공간',
            'brand.imagery.teamDesc': '오피스와 멤버들의 실제 사진. 자연스럽고, 연출되지 않은, 진정성 있는. 스톡 사진은 절대 사용하지 않습니다.',
            'brand.imagery.motionTitle': '정지보다 모션',
            'brand.imagery.motionDesc': '벡터, Lottie, 코드 기반 비주얼이 우선입니다. 사진과 스크린샷은 실제를 보여줄 때만 사용합니다. 실제 제품, 실제 사람들, 실제 공간.',
            'brand.imagery.bullet1': '벡터, Lottie, 코드 기반 비주얼이 우선입니다.',
            'brand.imagery.bullet2': '사진과 스크린샷은 실제를 보여줄 때만 사용합니다. 실제 제품, 실제 사람들, 실제 공간.',
            'brand.downloads.logoGenerator': '로고 생성기',
            'brand.downloads.logoGeneratorDesc': '공식 브랜드 자산을 커스터마이징하고 다운로드하세요. 타입을 선택하고 색상을 고른 뒤 고해상도 PNG를 받으세요.',
            'brand.downloads.iconGenerator': '아이콘 생성기',
            'brand.downloads.iconGeneratorDesc': '일관된 아이콘을 검색하고 생성하세요. 리워드, 포인트, 게임 관련 인터페이스에 최적화되어 있습니다.',
            'brand.downloads.isometricGenerator': '아이소메트릭 생성기',
            'brand.downloads.isometricGeneratorDesc': '로고 마크의 3D 아이소메트릭 버전을 생성합니다. 각도와 원근감을 조정하여 구성에 맞게 사용하세요.',
            'brand.downloads.comingSoon': '곧 출시',
            'brand.logoGenerator.title': '로고 생성기',
            'brand.logoGenerator.description': '공식 브랜드 자산을 커스터마이징하고 다운로드하세요. 타입을 선택하고 색상을 고른 뒤 고해상도 PNG를 받으세요.',
            'brand.logoGenerator.assetType': '자산 유형',
            'brand.logoGenerator.mark': '로고 마크',
            'brand.logoGenerator.wordmark': '워드마크',
            'brand.logoGenerator.color': '색상',
            'brand.logoGenerator.customHex': '커스텀 헥스',
            'brand.logoGenerator.download': 'PNG 다운로드 (512px 높이)',
            'brand.iconGenerator.title': '아이콘 생성기',
            'brand.iconGenerator.description': '일관된 아이콘을 검색하고 생성하세요. 리워드, 포인트, 게임 관련 인터페이스에 최적화되어 있습니다.',
            'brand.iconGenerator.searchLabel': '라이브러리 검색',
            'brand.iconGenerator.searchPlaceholder': '아이콘 검색 (예: Calendar, User, Gift...)',
            'brand.iconGenerator.results': '결과',
            'brand.iconGenerator.popular': '인기 아이콘',
            'brand.iconGenerator.noResults': '"{query}"에 대한 아이콘을 찾을 수 없습니다',
            'brand.iconGenerator.loadMore': '더 보기',
            'brand.iconGenerator.weight': '굵기',
            'brand.iconGenerator.color': '색상',
            'brand.iconGenerator.customHex': '커스텀 헥스',
            'brand.iconGenerator.download': 'PNG 다운로드',
            'brand.iconGenerator.preview': '미리보기',
            'brand.isometricGenerator.title': '아이소메트릭 투영',
            'brand.isometricGenerator.description': '로고 마크의 정사영 아이소메트릭 투영을 생성합니다. 결과물은 브랜드에 안전하고, 반복 가능하며, 작은 크기에서도 선명합니다.',
            'brand.isometricGenerator.angle': '각도',
            'brand.isometricGenerator.direction': '방향',
            'brand.isometricGenerator.download': 'PNG 다운로드 (512px)',
            'brand.isometricGenerator.angleSubtle': '은은함',
            'brand.isometricGenerator.angleStandard': '표준',
            'brand.isometricGenerator.angleStrong': '강함',
            'brand.isometricGenerator.dirLeft': '왼쪽',
            'brand.isometricGenerator.dirCenter': '가운데',
            'brand.isometricGenerator.dirRight': '오른쪽',
            'brand.isometricGenerator.color': '색상',
            'brand.isometricGenerator.customHex': '커스텀',
            'brand.isometricGenerator.dirTopRight': '우측 상단',
            'brand.isometricGenerator.dirTopLeft': '좌측 상단',
            'brand.isometricGenerator.dirBottomRight': '우측 하단',
            'brand.isometricGenerator.dirBottomLeft': '좌측 하단',
            'brand.isometricGenerator.depth': '깊이',
            'brand.isometricGenerator.depthHint': '마크의 치수 오프셋을 조절합니다.',
            'brand.isometricGenerator.edgeStyle': '엣지 스타일',
            'brand.isometricGenerator.edgeSharp': '샤프',
            'brand.isometricGenerator.edgeSoft': '소프트',
            'brand.isometricGenerator.edgeOutline': '아웃라인만',
            'brand.isometricGenerator.faceColor': '면 색상 모드',
            'brand.isometricGenerator.faceFlat': '플랫',
            'brand.isometricGenerator.faceSubtle': '은은한 음영',
            'brand.isometricGenerator.faceStroke': '스트로크만',
            'brand.isometricGenerator.brandSafe': '브랜드 안전',
            
            // Product
            'product.hero.tag': '제품 디자인 시스템',
            'product.hero.title': '심플. 아이코닉.\n딜라이트풀.',
            'product.hero.description': '모든 인터랙션은 목적이 있고, 모든 화면은 신뢰를 줍니다. 관심을 얻고 보답하는 경험을 디자인합니다.',
            'product.hero.cta': '원칙 살펴보기',
            'product.sections.principles': '원칙',
            'product.sections.patterns': '패턴',
            'product.sections.conventions': '컨벤션',
            'product.sections.resources': '리소스',
            'product.intro.catchphrase': '사용자가 참여하고 싶어하는 즐거운 경험을 디자인합니다.',

            // Interaction Layers
            'product.layers.title': '인터랙션 레이어',
            'product.layers.subtitle': '모든 기능은 두 개의 고유한 레이어로 구성되어 일관되고 기억에 남는 경험을 만듭니다.',
            'product.layers.phase1.title': '이것은 기능입니다',
            'product.layers.phase1.subtitle': '인게이지먼트 기능, 미션 흐름, 리워드 피드백',
            'product.layers.phase2.delivery': '기능은 거의 항상 Delivery UX 레이어로 구성됩니다.',
            'product.layers.phase2.deliveryEn': '그리드, 내비게이션, 로딩 상태, 전환',
            'product.layers.phase2.signature': '그리고 Signature UX 레이어',
            'product.layers.phase2.signatureEn': '게이미피케이션, 모먼트, 아이코닉 인터랙션',
            'product.layers.delivery.title': 'Delivery 레이어',
            'product.layers.delivery.label': '간단하고 친숙하며 신뢰할 수 있는',
            'product.layers.delivery.bullet1': '내비게이션, 레이아웃, 컨테이너, 그리드, 로딩 상태, 전환',
            'product.layers.delivery.bullet2': '매우 다른 Signature 경험 전반에 걸친 일관성',
            'product.layers.delivery.bullet3': '패키징, 테마, 구조',
            'product.layers.delivery.bullet4': '속도, 안정성, 재사용을 위해 설계',
            'product.layers.signature.title': 'Signature 레이어',
            'product.layers.signature.label': '아이코닉 & 딜라이트풀',
            'product.layers.signature.bullet1': '아이코닉하고 참여도 높은 인터랙션',
            'product.layers.signature.bullet2': '차별화된 메커닉 (게이미피케이션, 미션, 모먼트)',
            'product.layers.signature.bullet3': '창의성과 실험이 살아있는 곳',
            'product.layers.signature.bullet4': '재사용 가능한 블록으로 구성되지 않음',
            'product.sections.layers': '컴포지션',
            'product.sections.chameleon': '변수',

            'product.chameleon.title': '변수',
            'product.chameleon.description': '우리의 제품은 각각 고유한 브랜드를 가진 수백 개의 파트너를 지원합니다. 카멜레온은 토큰 기반 테마 전략으로, 모든 화면을 구동하는 구조화된 디자인 토큰 세트입니다. 색상, 간격, 모서리 곡률, 그림자, 타이포그래피. 완전히 커스터마이즈 가능하면서도 항상 일관적입니다.',
            'product.chameleon.presets': '테마 프리셋',
            'product.chameleon.grabLabel': 'URL에서 가져오기',
            'product.chameleon.tokens': '토큰 세트',
            'product.chameleon.preview': '라이브 미리보기',

            // Patterns
            'product.patterns.title': '패턴',
            'product.patterns.description': '모든 버즈빌 제품의 외형과 동작을 정의하는 통합 인터랙션 및 시각 패턴 라이브러리입니다. UX와 비주얼을 분리하지 않고 하나의 연결된 시스템으로 다룹니다. 모든 것이 하나의 브라우저블 라이브러리에 있습니다.',
            'product.patterns.library': '버즈빌 패턴 라이브러리',
            'product.patterns.libraryDesc': '완전한 브라우저블 패턴 라이브러리는 내부에서 유지관리됩니다. 접근은 버즈빌 팀원으로 제한됩니다.',
            'product.patterns.comingSoon': 'Coming soon',

            'product.patterns.interaction.title': '인터랙션 패턴',
            'product.patterns.interaction.intro': '화면을 그리기 전에 먼저 동작을 정의합니다. 인터랙션 패턴은 모든 제품 화면의 동작 뼈대입니다. 사용자가 플로우에 진입하는 방식, 콘텐츠 로딩 중 일어나는 일, 피드백이 전달되는 방법, 모든 전환의 물리를 관장합니다. 이 카테고리는 마이크로 인터랙션도 포함합니다: 숨쉬는 아이콘, 튀어오르는 카운터, 딸깍 맞물리는 스와이프 같은 작지만 보이지 않는 디테일이 모여 완성된 제품의 느낌을 만듭니다. 이 패턴이 일관될 때, 사용자는 이를 인식하지 못합니다. 그것이 목표입니다.',

            'product.patterns.uikit.title': 'UI 키트',
            'product.patterns.uikit.intro': 'UI 키트는 인터랙션 패턴이 실체화되는 곳입니다. 모든 컴포넌트는 상위에서 정의된 특정 동작 목적을 위해 존재합니다. Atom은 가장 작은 단위로, 버튼은 로딩, 비활성, 성공 상태를 전달할 줄 압니다. Module은 Atom을 캠페인 카드나 리워드 로우 같은 독립 단위로 조합합니다. View는 Module을 풀스크린으로 조율합니다. 키트는 처음부터 카멜레온 테마를 위해 구축되었습니다. 모든 컴포넌트가 토큰 오버라이드를 수용하고, 브레이크포인트에 반응하며, 구조적 동일성을 잃지 않으면서 플랫폼 컨벤션에 적응합니다.',

            'product.patterns.visual.title': '비주얼 랭귀지',
            'product.patterns.visual.intro': '우리가 제작하는 모든 시각 자산은 테마 시스템 안에서 살아가도록 설계됩니다. 아이콘, 일러스트레이션, 장식 요소는 퍼블리셔의 브랜드가 적용될 때 자동으로 적응하는 색상 구조로 구축됩니다. 같은 선물 상자가 네 가지 다른 팔레트로 렌더링되어, 각각의 맥락에서 자연스럽게 느껴집니다. 타이포그래피, 계층 구조, 이미지도 같은 원칙을 따릅니다: 기본적으로 파라메트릭하여, 수백 개의 파트너 브랜드에 걸친 시각적 일관성이 노력이 아닌 당연한 것이 됩니다.',

            // Conventions
            'product.conventions.title': '컨벤션',
            'product.conventions.description': '디자인 시스템을 건강하게 유지하고 팀의 정렬을 보장하는 공유 의식, 프로세스, 표준입니다. 해석을 위한 가이드라인이 아니라 따라야 할 합의입니다.',
            'product.conventions.workflow.title': '디자인 워크플로우',
            'product.conventions.workflow.desc': '모든 기능은 탐색에서 프로덕션까지 구조화된 경로를 따릅니다. 디자인 리뷰와 핸드오프가 후순위가 아닌 공식 체크포인트로 통합되어 있습니다.',
            'product.conventions.workflow.bulletCount': '6',
            'product.conventions.workflow.bullet1': '디스커버리: 문제 프레이밍, 경쟁 분석, 사용자 리서치 종합.',
            'product.conventions.workflow.bullet2': '와이어프레임: 비주얼 작업 전 프로덕트 및 엔지니어링과 검증된 로우 피델리티 플로우.',
            'product.conventions.workflow.bullet3': '비주얼 디자인: 실제 토큰과 컴포넌트를 사용하여 패턴 라이브러리에서 구축된 하이 피델리티 화면.',
            'product.conventions.workflow.bullet4': '디자인 리뷰: 주간 팀 크리틱과 격주 교차 팀 리뷰. 공유 패턴 변경은 디자인 리드의 합의 필요.',
            'product.conventions.workflow.bullet5': '핸드오프: Figma에서 토큰 참조, 레드라인, 인터랙티브 프로토타입이 포함된 주석 달린 스펙 전달. 매 스프린트 전 핸드오프 미팅.',
            'product.conventions.workflow.bullet6': 'QA: 릴리스 전 스테이징에서 디자인 측 비주얼 QA. 스펙 대비 픽셀 수준 확인.',
            'product.conventions.tokens.title': '토큰 거버넌스',
            'product.conventions.tokens.desc': '디자인 토큰은 디자인과 코드를 연결하는 단일 진실의 원천입니다. 무결성이 중요하므로 추가, 수정, 삭제는 공식 프로세스를 따릅니다.',
            'product.conventions.tokens.bulletCount': '5',
            'product.conventions.tokens.bullet1': '모든 토큰은 Figma와 코드베이스 간에 동기화되는 버전 관리된 JSON 파일에 있습니다.',
            'product.conventions.tokens.bullet2': '새 토큰은 디자인 시스템 팀이 검토하는 제안서(이름, 값, 근거)가 필요합니다.',
            'product.conventions.tokens.bullet3': '브레이킹 체인지(이름 변경, 삭제, 값 변경)는 최소 한 릴리스 주기의 디프리케이션 기간을 거칩니다.',
            'product.conventions.tokens.bullet4': '에일리어스 토큰(예: {theme/primary})이 원시 값보다 선호됩니다. 컴포넌트는 hex나 px를 하드코딩하지 않습니다.',
            'product.conventions.tokens.bullet5': '분기별 토큰 감사를 실행하여 미사용, 중복, 불일치 항목을 식별합니다.',
            'product.conventions.naming.title': '네이밍 컨벤션',
            'product.conventions.naming.desc': '일관된 네이밍은 인지 부하를 줄이고 시스템을 검색, 스크립팅, 예측 가능하게 만듭니다. 시스템의 모든 아티팩트가 같은 규칙을 따릅니다.',
            'product.conventions.naming.bulletCount': '5',
            'product.conventions.naming.bullet1': '토큰: kebab-case, 시각적이 아닌 시맨틱. "blue" 대신 "primary", "dark-text" 대신 "base-content" 사용.',
            'product.conventions.naming.bullet2': 'Figma 레이어: 컴포넌트 또는 토큰 이름과 일치하는 kebab-case. "Frame 47"이나 "Group 12" 금지.',
            'product.conventions.naming.bullet3': '컴포넌트: 코드에서 PascalCase, Figma에서 kebab-case. 외형이 아닌 목적을 설명하는 이름 (예: RedCircle이 아닌 RewardBadge).',
            'product.conventions.naming.bullet4': '파일 & 브랜치: 브랜치는 feature/[scope]-[description], 디자인 파일은 kebab-case (예: mission-flow-v2.fig).',
            'product.conventions.naming.bullet5': '아이콘: [category]/[name]-[size] (예: navigation/arrow-left-24). 항상 그리드 사이즈를 이름에 포함.',
            'product.conventions.versioning.title': '버전 관리 & 체인지로그',
            'product.conventions.versioning.desc': '디자인 시스템의 모든 릴리스는 시맨틱 버전으로 관리되어 소비자가 무엇이 변경되었고 조치가 필요한지 정확히 알 수 있습니다.',
            'product.conventions.versioning.bulletCount': '5',
            'product.conventions.versioning.bullet1': '시맨틱 버전 관리: 브레이킹 체인지는 MAJOR, 새 토큰/컴포넌트는 MINOR, 버그 수정 및 개선은 PATCH.',
            'product.conventions.versioning.bullet2': '모든 릴리스에 추가, 수정, 디프리케이션, 삭제를 기록하는 공개 체인지로그가 동반됩니다.',
            'product.conventions.versioning.bullet3': 'Figma 라이브러리 버전은 추적을 위해 코드 패키지와 동일한 버전 번호로 태그됩니다.',
            'product.conventions.versioning.bullet4': '디프리케이션 알림은 삭제 최소 한 마이너 버전 전에 마이그레이션 가이드와 함께 게시됩니다.',
            'product.conventions.versioning.bullet5': '릴리스 주기: 스프린트 경계에 맞춘 격주 마이너 릴리스, 필요 시 패치.',

            'product.principles.alignmentQuestionLabel': '정렬 질문',
            'product.principles.simple.shortTitle': '심플',
            'product.principles.simple.title': 'Simple',
            'product.principles.simple.description': '디자인은 즉시 이해 가능해야 합니다. 두 가지 방법이 있다면 더 단순한 것을 선택합니다. 사용자는 사전 지식, 숨겨진 비결, 또는 집중적인 주의 없이 탐색할 수 있어야 합니다. 심플함은 깔끔함, 접근성, 예측 가능성을 의미합니다. 풍부한 상호작용이나 다중 미션 흐름에서도 경로는 명확해야 합니다.',
            'product.principles.simple.alignmentQuestion': '할머니도 도움 없이 사용할 수 있을까요?',
            'product.principles.iconic.shortTitle': '아이코닉',
            'product.principles.iconic.title': 'Iconic',
            'product.principles.iconic.description': '우리 작업은 독특하고, 고품질이며, 즉시 인식 가능해야 합니다. 핵심 대상에게 현대적이고 자신감 있고 관련성 있게 느껴지는 디자인을 목표로 합니다. 화면이 어떤 경쟁사 제품에 속한 것처럼 보인다면, 아직 완성되지 않은 것입니다.',
            'product.principles.iconic.alignmentQuestion': '사람들이 공유하거나 참조할 만한 것일까요?',
            'product.principles.delightful.shortTitle': '딜라이트풀',
            'product.principles.delightful.title': 'Delightful',
            'product.principles.delightful.description': '상호작용은 기계적이 아닌 즐거움을 주어야 합니다. 딜라이트는 장식이 아닙니다. 적절한 타이밍의 모션, 재미있는 피드백, 사용자를 보상받고 참여한다고 느끼게 하는 순간들입니다. 속도나 명확성을 방해해서는 안 됩니다.',
            'product.principles.delightful.alignmentQuestion': '진정으로 재미있고 참여를 유도할까요?',
            'product.principles.purposeful.shortTitle': '퍼포스풀',
            'product.principles.purposeful.title': 'Purposeful',
            'product.principles.purposeful.description': '모든 경험은 명확하고 의미 있는 가치를 전달해야 합니다. 사용자가 투자하는 시간과 노력이 가치 있어야 합니다. 보상 중심 생태계에서 가치는 명확하고, 즉각적이며, 공정해야 합니다. 흐름이 일처럼 느껴지거나, 보상이 정당화되지 않거나, 혜택이 충분히 보이지 않는다면 우리는 모두의 시간을 낭비하는 것입니다.',
            'product.principles.purposeful.alignmentQuestion': '사용자의 시간에 가치가 있나요, 아니면 이유 없이 노력을 만드는 건가요?',
            'product.principles.trustworthy.shortTitle': '트러스트워디',
            'product.principles.trustworthy.title': 'Trustworthy',
            'product.principles.trustworthy.description': '사용자는 퍼널을 이동해도 항상 안전하고, 방향을 알고, 자신감을 느껴야 합니다. 우리 경험은 앱, 웹, 하이브리드 전환에 걸쳐 있습니다. 디자인은 통합되고 안정적이어야 사용자가 의심스러운 서드파티 영역에 떨어졌는지 궁금해하지 않습니다. 신뢰는 일관성, 부드러움, 톤, 예측 가능한 행동에서 옵니다.',
            'product.principles.trustworthy.alignmentQuestion': '일반 사용자가 처음부터 끝까지 이 흐름을 신뢰할 수 있을까요, 아니면 다른 제품으로 순간이동한 것처럼 느껴지나요?',

            // New submenu items
            'nav.product.uxPatterns': 'UX 패턴',
            'nav.product.visualPatterns': '시각적 패턴',
            'nav.product.workflowRituals': '워크플로우 & 의식',
            
            // Page-specific translations
            'pages.backToGuidelines': '가이드라인으로 돌아가기',
            'pages.sections.interactionPatterns': '상호작용 패턴',
            'pages.sections.uiKit': 'UI 키트',
            'pages.sections.microInteractions': '마이크로 상호작용',
            'pages.sections.designPrinciples': '디자인 원칙',
            'pages.sections.visualGuidelines': '시각적 가이드라인',
            'pages.sections.comingSoon': '곧 출시',
            'pages.sections.corePrinciples': '핵심 원칙',
            'pages.sections.workflowSteps': '워크플로우 단계',
            
            // Interaction Patterns specific
            'interactionPatterns.whileLoading': '로딩 중',
            'interactionPatterns.whileLoading.description': '사용자가 대기하는 동안 참여를 유지하는 스켈레톤 화면, 로딩 상태, 점진적 공개 패턴입니다.',
            'interactionPatterns.pageScroll': '페이지 스크롤',
            'interactionPatterns.pageScroll.description': '패럴랙스와 공개 애니메이션을 포함한 주요 상호작용 패턴으로서의 기본 세로 스크롤입니다.',
            'interactionPatterns.notify': '알림',
            'interactionPatterns.notify.description': '사용자 플로우를 방해하지 않고 피드백을 제공하는 토스트 알림, 배너, 시스템 메시지입니다.',
            'interactionPatterns.alert': '경고',
            'interactionPatterns.alert.description': '즉각적인 사용자 주의와 조치가 필요한 중요한 알림과 경고입니다.',
            'interactionPatterns.pauseAsk': '일시정지 & 질문',
            'interactionPatterns.pauseAsk.description': '정보를 수집하거나 작업을 확인하기 위해 사용자 플로우를 일시 중지하는 모달 대화상자와 팝업입니다.',
            'interactionPatterns.magnify': '확대',
            'interactionPatterns.magnify.description': '추가 정보나 옵션을 보여주는 확장 가능한 콘텐츠와 바텀시트입니다.',
            'interactionPatterns.screenToScreen': '화면 간 이동',
            'interactionPatterns.screenToScreen.description': '명확한 네비게이션 계층을 가진 다른 뷰나 화면 간의 부드러운 전환입니다.',
            'interactionPatterns.feedback': '피드백',
            'interactionPatterns.feedback.description': '반응적인 경험을 만들기 위한 사용자 상호작용에 대한 즉각적인 시각적 또는 햅틱 피드백입니다.',
            'interactionPatterns.moreToCome': '더 많은 패턴 예정',
            'interactionPatterns.moreToCome.description': '새로운 상호작용 요구를 발견하고 문서화함에 따라 추가 패턴이 추가될 예정입니다.',
            
            // UI Kit specific
            'uiKit.atoms': '원자',
            'uiKit.molecules': '분자',
            'uiKit.organisms': '유기체',
            'uiKit.templates': '템플릿',
            'uiKit.pages': '페이지',
            'uiKit.moreToCome': '더 많은 컴포넌트 예정',
            
            // Micro-interactions specific
            'microInteractions.livingIcons': '살아있는 아이콘',
            'microInteractions.emphasisOn': '강조',
            'microInteractions.rewardDelights': '보상 기쁨',
            'microInteractions.moreToCome': '더 많은 패턴 예정',
            
            // Code preview
            'codePreview.title': '코드 예제',
            'codePreview.copy': '복사',
            'codePreview.copied': '복사됨!',
            
            // Live preview
            'livePreview.title': '라이브 미리보기',
            'livePreview.comingSoon': '미리보기 곧 출시',
            
            // Footer
            'footer.description': '버즈빌의 디자인 진실의 원천이 되는 곳입니다. 우리는 공개적으로 구축합니다. 이 포털은 주로 내부적으로 그리고 파트너들이 사용하도록 의도되었지만, 우리가 어떻게 일하는지 누구나 살펴볼 수 있기를 좋아합니다!',
            'footer.foundations.mission': '미션',
            'footer.foundations.philosophy': '마인드셋',
            'footer.foundations.values': '작업 원칙',
            'footer.foundations.team': '우리의 팀',
            'footer.foundations.tools': '우리의 스택',
            'footer.brand.principles': '원칙',
            'footer.brand.guidelines': '가이드라인',
            'footer.brand.resources': '리소스',
            'footer.product.principles': '원칙',
            'footer.product.guidelines': '가이드라인',
            'footer.product.resources': '리소스',
            'footer.connect.buzzvil': '버즈빌',
            'footer.connect.contact': '연락처',
            'footer.connect.careers': '채용',
            'footer.connect.figma': 'Figma',
            'footer.connect.github': 'GitHub',
            'footer.connect.linkedin': 'LinkedIn',
            'footer.made': '만든',
            'footer.by': '버즈빌 디자인 팀',
            'footer.privacy': '개인정보 보호정책',
            'footer.terms': '서비스 약관',
            'footer.about': '사이트 소개',

            // About page
            'about.kicker': '사이트 소개',
            'about.title': '이 사이트는 어떻게 만들어졌나요',
            'about.description': 'Design Buzzvil은 버즈빌의 살아있는 디자인 포털입니다. 브랜드, 제품 원칙, 디자인 시스템을 이중 언어, 풀 애니메이션, 정적으로 내보내는 웹사이트로 문서화합니다. 내부 구조를 살펴보세요.',
            'about.contributors': '기여자',
            'about.contributorNote': '유일한 저자이자 관리자. 미래 협력자를 환영합니다.',
            'about.techStack': '기술 스택',
            'about.architecture': '아키텍처 및 로직',
            'about.viewSource': 'GitHub에서 소스 보기',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ko')) {
      setLanguage(savedLanguage);
    } else {
      // Auto-detect browser language if no saved preference
      const browserLanguage = navigator.language || navigator.languages?.[0] || 'en';
      const detectedLanguage = browserLanguage.startsWith('ko') ? 'ko' : 'en';
      setLanguage(detectedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language to localStorage when it changes
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const getFontClass = (): string => {
    return language === 'ko' ? 'font-pretendard' : 'font-nunito';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getFontClass }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
