'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getFontClass: () => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Navigation
    'nav.foundations': 'Foundations',
    'nav.brand': 'Brand',
    'nav.product': 'Product',
    'nav.team': 'Team',
    'nav.tools': 'Tools',
    'nav.sections.mission': 'The Mission',
    'nav.sections.philosophy': 'Our Mindset',
    'nav.sections.values': 'Working Principles',
    'nav.sections.team': 'Our Team',
    'nav.sections.tools': 'Our Stack',
    
    // Contact Banner
    'banner.title': 'Want to meet us over coffee?',
    'banner.cta': 'Schedule a meeting',
    'banner.cta.short': 'Contact',
    'banner.requirements.schedule': 'Schedule a time',
    'banner.requirements.info': 'Include your info',
    
    // Hero
    'hero.title': 'Buzzvil Design',
    'hero.subtitle': 'Engaging. Playful. Scalable.',
    'hero.sentence.start': 'We build',
    'hero.sentence.end': 'experiences.',
    'hero.keyword.engaging': 'Engaging',
    'hero.keyword.playful': 'Playful',
    'hero.keyword.scalable': 'Scalable',
            'hero.explore': 'Explore Foundations',
            'hero.brand': 'Brand',
            'hero.product': 'Product',
            'hero.scroll': 'Scroll to explore',
    
            // Mission & Vision
            'mission.title': 'Mission & Vision',
            'mission.subtitle': 'Our mission and vision guide everything we do at Buzzvil.',
            'mission.mission.title': 'Mission',
            'mission.mission.subtitle': 'what we do now',
            'mission.mission.content': 'We design meaningful interactions that shape how people discover, experience, and stay connected with Buzzvil\'s campaigns and brand.\nOur goal is to turn advertising into experiences people choose to explore—moments that capture attention, spark curiosity, and drive real results for advertisers.',
            'mission.vision.title': 'Vision',
            'mission.vision.subtitle': 'what future we\'re building',
            'mission.vision.content': 'We set the next standard for AdTech design by transforming ads and brand touchpoints into engaging, repeatable experiences that connect users and advertisers.\nWe envision a future where advertising feels natural, enjoyable, and seamlessly part of everyday life.',
    
            // Philosophy
            'philosophy.title': 'Philosophy',
            'philosophy.subtitle': 'how we approach it',
            'philosophy.content': 'At Buzzvil, design shapes how people experience advertising, not as interruptions, but as moments of connection and delight.\nWe believe every touchpoint, from brand to product, should feel playful, engaging, and effortless.\nOur role is to unify how Buzzvil looks, feels, and behaves across the ecosystem, building trust, driving performance, and inspiring what AdTech can become.',
    
            // Ways of Working
            'waysOfWorking.title': 'Ways of Working',
            'waysOfWorking.subtitle': 'How we think, create, and collaborate at Buzzvil Design.',
            'waysOfWorking.principles.title': 'Our Principles',
            'waysOfWorking.principles.subtitle': 'How we work together to design at Buzzvil.',
            'waysOfWorking.team.title': 'Our Team',
            'waysOfWorking.team.subtitle': 'The people behind Buzzvil Design.',
            'waysOfWorking.stack.title': 'Our Stack',
            'waysOfWorking.stack.subtitle': 'The tools that power our design work.',
    
    // Principles
    'principles.title': 'Principles',
    'principles.subtitle': 'The principles that guide our approach to design and development.',
    'principles.reward.title': 'Reward = Time',
    'principles.reward.shortTitle': 'Reward',
    'principles.reward.content': 'Rewards are a transparent and measurable exchange of user attention. Mechanism: 1P ≈ 1 second of attention. This gives consistency to users and predictability to advertisers.',
    'principles.delight.title': 'Delight Without Deception',
    'principles.delight.shortTitle': 'Delight',
    'principles.delight.content': 'Rewards spark motivation, but experiences sustain engagement. We never use dark patterns: never overlay one ad on another, never mislead, never trap. Interactions must feel playful, clear, and respectful.',
    'principles.scalable.title': 'Scalable by Design',
    'principles.scalable.shortTitle': 'Scalable',
    'principles.scalable.content': 'Every design decision must scale across products, partners, and business models. We provide meaningful customization, but avoid unsustainable exceptions. These principles can veto business or product decisions that fragment the system.',
    
    // Principles Characteristics
    'principles.reward.characteristics.0': 'Transparent Exchange',
    'principles.reward.characteristics.1': 'Measurable Attention',
    'principles.reward.characteristics.2': 'User Consistency',
    'principles.reward.characteristics.3': 'Advertiser Predictability',
    'principles.delight.characteristics.0': 'No Dark Patterns',
    'principles.delight.characteristics.1': 'Playful Interactions',
    'principles.delight.characteristics.2': 'Clear Communication',
    'principles.delight.characteristics.3': 'Respectful Design',
    'principles.scalable.characteristics.0': 'Cross-Product Scale',
    'principles.scalable.characteristics.1': 'Meaningful Customization',
    'principles.scalable.characteristics.2': 'System Integrity',
    'principles.scalable.characteristics.3': 'Decision Veto Power',
    
    // Values
            'values.title': 'Working Principles',
    'values.subtitle': 'How we work together to design at Buzzvil.',
            'values.build.title': 'Build in the Open',
            'values.build.shortTitle': 'Build in the Open',
    'values.build.content': 'We start rough, share early, and iterate fast. Every designer has access to AI tools that accelerate exploration. Feedback and quick loops help us refine ideas into solid, production-ready solutions.',
    'values.build.tagline': 'iterate fast.',
    'values.clarity.title': 'Clarity Through Feedback',
    'values.clarity.shortTitle': 'Be Crystal Clear',
    'values.clarity.content': 'We communicate with candor and precision. Feedback is how we grow: giving it clearly, receiving it openly, and applying it constructively. Clear communication builds trust and avoids wasted effort.',
    'values.clarity.tagline': 'Clarity first, feedback always.',
    'values.grit.title': 'Own it, Ship It',
    'values.grit.shortTitle': 'Own it, Ship It',
    'values.grit.content': 'Designers don\'t just stop at drafts. We take ownership of user stories and projects, pushing them from first sketches through to production. We lead with persistence and craft until the outcome is real.',
    'values.grit.tagline': 'Grit.',
    'values.explore.title': 'Bold Explorers',
    'values.explore.shortTitle': 'Explorers',
    'values.explore.content': 'We embrace research, experimentation, and AI adoption as core to our craft. With powerful tools and a culture of inquiry, we have no excuse not to explore widely, validate rigorously, and design with confidence.',
    'values.explore.tagline': 'Explore boldly, research deeply.',
    'values.team.title': 'One-UX',
    'values.team.shortTitle': 'One-UX',
    'values.team.content': 'We align as a design team before we scale out. That means syncing often, sharing conventions, and applying consistent practices. Our alignment ensures partners, users, and advertisers experience Buzzvil design as one coherent system.',
    'values.team.tagline': 'Align first, scale together.',
    
    // Values Characteristics
    'values.build.characteristics.0': 'Rapid Prototyping',
    'values.build.characteristics.1': 'AI-Powered Exploration',
    'values.build.characteristics.2': 'Early Sharing',
    'values.build.characteristics.3': 'Quick Iteration',
    'values.clarity.characteristics.0': 'Candor & Precision',
    'values.clarity.characteristics.1': 'Open Communication',
    'values.clarity.characteristics.2': 'Constructive Growth',
    'values.clarity.characteristics.3': 'Trust Building',
    'values.grit.characteristics.0': 'Full Ownership',
    'values.grit.characteristics.1': 'End-to-End Delivery',
    'values.grit.characteristics.2': 'Persistence',
    'values.grit.characteristics.3': 'Production Focus',
    'values.explore.characteristics.0': 'Research-Driven',
    'values.explore.characteristics.1': 'AI Adoption',
    'values.explore.characteristics.2': 'Wide Exploration',
    'values.explore.characteristics.3': 'Rigorous Validation',
    'values.team.characteristics.0': 'Team Alignment',
    'values.team.characteristics.1': 'Shared Conventions',
    'values.team.characteristics.2': 'Consistent Practices',
    'values.team.characteristics.3': 'Coherent System',
    
    // Resources
    'resources.title': 'Design Resources',
    'resources.subtitle': 'Everything you need to create exceptional user experiences. Download our latest design files, guidelines, and templates.',
    'resources.category.design-system': 'Design System',
    'resources.category.templates-patterns': 'Templates & Patterns',
    'resources.category.brand-assets': 'Brand & Assets',
    
    // Team
    'team.title': 'Meet Our Design Team',
    'team.subtitle': 'A diverse group of creative minds working together to create exceptional user experiences and drive design excellence.',
    
    // Tools
    'tools.title': 'Our Stack',
    'tools.subtitle': 'The tools that power our design work.',
    'tools.visit': 'Visit Tool',
    'tools.category.design-development': 'Design & Development Tools',
    
            // Brand
            'brand.sections.principles': 'Principles',
            'brand.sections.guidelines': 'Guidelines',
            'brand.sections.resources': 'Resources',
            'brand.intro.catchphrase': 'Shaping how Buzzvil looks, feels, and behaves across every touchpoint.',
            'brand.principles.title': 'Brand Principles',
            'brand.principles.description': 'Our core brand principles that guide every decision, interaction, and experience we create. These fundamental values ensure consistency and authenticity across all touchpoints.',
            'brand.guidelines.title': 'Brand Guidelines',
            'brand.guidelines.description': 'Comprehensive guidelines for applying our brand consistently across all platforms and touchpoints. From logo usage to color palettes, typography, and voice.',
            'brand.resources.title': 'Brand Resources',
            'brand.resources.description': 'Download our brand assets, templates, and resources. Everything you need to implement our brand consistently across your projects and campaigns.',
            
            // Brand guidelines (Identity System 2.0)
            'brand.hero.tag': 'Identity System 26.1',
            'brand.hero.title': 'Calm and Iconic. Always in Context.',
            'brand.hero.description': 'Built on product behavior, our brand is context-native. Calm when it blends in, iconic when clarity demands it.',
            'brand.hero.cta': 'Explore Guidelines',
            'brand.nav.logo': 'Logo',
            'brand.nav.colors': 'Colors',
            'brand.nav.typography': 'Typography',
            'brand.nav.imagery': 'Imagery',
            'brand.nav.downloads': 'Downloads',
            'brand.logo.title': 'The Chameleon',
            'brand.logo.description': 'The logo is chameleon-like. It adapts to its environment, taking on black or white depending on the background. While it can take on primary or secondary colors in specific partner contexts, we default to the monochrome usage to maintain our clean brand aesthetic.',
            'brand.logo.lightBg': 'On Light Background',
            'brand.logo.darkBg': 'On Dark Background',
            'brand.logo.partnerContext': 'Partner Context Examples',
            'brand.logo.kakaoBank': 'KakaoBank',
            'brand.logo.kBank': 'K Bank',
            'brand.logo.oliveYoung': 'Olive Young',
            'brand.logo.clearspace': 'Clearspace',
            'brand.logo.clearspaceDesc': 'Always maintain generous clearspace around the logo to ensure legibility and impact.',
            'brand.logo.unacceptable': 'Unacceptable Usage',
            'brand.logo.unacceptableDesc': 'To maintain brand integrity, avoid manipulating the logo in ways that compromise its legibility or form.',
            'brand.logo.noStretch': 'Do not stretch',
            'brand.logo.noCrop': 'Do not crop',
            'brand.logo.noRotate': 'Do not rotate',
            'brand.logo.noDeform': 'Do not deform',
            'brand.logo.logoTreatment': 'Logo Treatment',
            'brand.logo.maskingTitle': 'Masking (Image & Video)',
            'brand.logo.maskingDesc': 'As part of our chameleon philosophy, we allow image, illustration, or video injection inside our logo shape. Ensure sufficient contrast with the background.',
            'brand.logo.threeDTitle': '3D Guidelines',
            'brand.logo.threeDDesc': 'We allow isometric 3D transformations to add depth. The aesthetic must remain abstract, simple, and tonal. Avoid free-form 3D distortion.',
            'brand.logo.isometricLabel': 'Isometric (Allowed)',
            'brand.logo.freeformLabel': 'Free-form 3D (Not Allowed)',
            'brand.colors.grayscale': 'Grayscale',
            'brand.colors.grayscaleDesc': 'Our primary palette. We aim for a high-contrast, clean look using almost exclusively black and white tones.',
            'brand.colors.red': 'Accent Red',
            'brand.colors.redDesc': 'Used sparingly for primary actions or critical alerts. Aim for <10% usage in any composition.',
            'brand.colors.orange': 'Accent Orange',
            'brand.colors.orangeDesc': 'Secondary accent color, complements the red. Use for banners or highlights.',
            'brand.colors.copied': 'Copied!',
            'brand.typography.primaryTitle': 'Primary: Pretendard / Inter',
            'brand.typography.primaryDesc': 'Pretendard for Korean, Inter for Latin. Our main typeface for its cleanliness, readability, and modern aesthetic. Works well in both headings and body text.',
            'brand.typography.h1Meta': 'Heading 1 / Bold / 48px',
            'brand.typography.h1Text': 'Ads That Work',
            'brand.typography.h2Meta': 'Heading 2 / Semibold / 36px',
            'brand.typography.h2Text': 'Where user benefit meets advertiser success',
            'brand.typography.bodyMeta': 'Body / Regular / 16px',
            'brand.typography.bodyText': 'Our logo is a chameleon. It can take any color from our customer/partners. By default and in the context of our brand, it takes the black or white depending on background.',
            'brand.typography.heroTitle': 'Display: Nunito (EN only)',
            'brand.typography.heroDesc': 'English-only typeface for navigation, hero headlines, and high-impact display text. Rounded and approachable, it adds warmth to key touchpoints.',
            'brand.typography.heroMeta': 'Header / Extrabold / 36px',
            'brand.typography.secondaryTitle': 'Secondary: Nanum Gothic Coding / Anonymous Pro',
            'brand.typography.secondaryDesc': 'Monospace typefaces to emphasize our tech roots. Nanum Gothic Coding for Korean, Anonymous Pro for Latin. Use for kickers, labels, numbers, code snippets, or technical data.',
            'brand.typography.kickerMeta': 'Kicker / Bold / 14px',
            'brand.typography.kickerText': 'Product Backend Team',
            'brand.typography.dataMeta': 'Data / Regular / 14px',
            'brand.imagery.title': 'Look & Feel',
            'brand.imagery.description': 'Our visuals are technical, sophisticated, and dark-themed. We use 3D abstract elements to represent data and infrastructure.',
            'brand.imagery.visualIdentity': 'Visual Identity Application',
            'brand.imagery.webInterface': 'Web Interface',
            'brand.downloads.logoGenerator': 'Logo Generator',
            'brand.downloads.logoGeneratorDesc': 'Customize and download the official brand assets. Select the type, choose a color, and get a high-resolution PNG.',
            'brand.downloads.iconGenerator': 'Icon Generator',
            'brand.downloads.iconGeneratorDesc': 'Search and generate consistent iconography. Optimized for reward, points, and game-related interfaces.',
            'brand.downloads.isometricGenerator': 'Isometric Generator',
            'brand.downloads.isometricGeneratorDesc': 'Generate a 3D isometric version of the logo mark. Adjust the angle and perspective to fit your composition.',
            'brand.downloads.comingSoon': 'Coming soon',
            'brand.logoGenerator.title': 'Logo Generator',
            'brand.logoGenerator.description': 'Customize and download the official brand assets. Select the type, choose a color, and get a high-resolution PNG.',
            'brand.logoGenerator.assetType': 'Asset Type',
            'brand.logoGenerator.mark': 'Logo Mark',
            'brand.logoGenerator.wordmark': 'Wordmark',
            'brand.logoGenerator.color': 'Color',
            'brand.logoGenerator.customHex': 'Custom Hex',
            'brand.logoGenerator.download': 'Download PNG (512px Height)',
            'brand.iconGenerator.title': 'Icon Generator',
            'brand.iconGenerator.description': 'Search and generate consistent iconography. Optimized for reward, points, and game-related interfaces.',
            'brand.iconGenerator.searchLabel': 'Search Library',
            'brand.iconGenerator.searchPlaceholder': 'Search icons (e.g. Calendar, User, Gift...)',
            'brand.iconGenerator.results': 'Results',
            'brand.iconGenerator.popular': 'Popular Icons',
            'brand.iconGenerator.noResults': 'No icons found for "{query}"',
            'brand.iconGenerator.loadMore': 'Load More',
            'brand.iconGenerator.weight': 'Weight',
            'brand.iconGenerator.color': 'Color',
            'brand.iconGenerator.customHex': 'Custom Hex',
            'brand.iconGenerator.download': 'Download PNG',
            'brand.iconGenerator.preview': 'Preview',
            'brand.isometricGenerator.title': 'Isometric Projection',
            'brand.isometricGenerator.description': 'Generate an orthographic isometric projection of the logo mark. Outputs remain brand-safe, repeatable, and legible at small sizes.',
            'brand.isometricGenerator.angle': 'Angle',
            'brand.isometricGenerator.direction': 'Direction',
            'brand.isometricGenerator.download': 'Download PNG (512px)',
            'brand.isometricGenerator.angleSubtle': 'Subtle',
            'brand.isometricGenerator.angleStandard': 'Standard',
            'brand.isometricGenerator.angleStrong': 'Strong',
            'brand.isometricGenerator.dirLeft': 'Left',
            'brand.isometricGenerator.dirCenter': 'Center',
            'brand.isometricGenerator.dirRight': 'Right',
            'brand.isometricGenerator.color': 'Color',
            'brand.isometricGenerator.customHex': 'Custom',
            'brand.isometricGenerator.dirTopRight': 'Top-right',
            'brand.isometricGenerator.dirTopLeft': 'Top-left',
            'brand.isometricGenerator.dirBottomRight': 'Bottom-right',
            'brand.isometricGenerator.dirBottomLeft': 'Bottom-left',
            'brand.isometricGenerator.depth': 'Depth',
            'brand.isometricGenerator.depthHint': 'Controls the dimensional offset of the mark.',
            'brand.isometricGenerator.edgeStyle': 'Edge Style',
            'brand.isometricGenerator.edgeSharp': 'Sharp',
            'brand.isometricGenerator.edgeSoft': 'Soft',
            'brand.isometricGenerator.edgeOutline': 'Outline only',
            'brand.isometricGenerator.faceColor': 'Face Color Mode',
            'brand.isometricGenerator.faceFlat': 'Flat',
            'brand.isometricGenerator.faceSubtle': 'Subtle shade',
            'brand.isometricGenerator.faceStroke': 'Stroke-only',
            'brand.isometricGenerator.brandSafe': 'Brand-safe',
            
            // Product
            'product.sections.principles': 'Principles',
            'product.sections.guidelines': 'Guidelines',
            'product.sections.resources': 'Resources',
            'product.intro.catchphrase': 'Designing delightful experiences that users love to engage with.',
            'product.guidelines.title': 'Product Guidelines',
            'product.guidelines.intro': 'Our Product experience gravitates around Interactions, and that is the core attribute to all of our experiences. We first define interaction patterns prior to even drafting a UI kit. Then will come polishing details like micro-interactions, coming on top of the UI kit.',
            
            'product.guidelines.uxPatterns.title': 'UX Patterns',
            'product.guidelines.uxPatterns.description': 'The core user experience patterns that define how users interact with our products. These patterns are established before any visual design work begins.',
            
            'product.guidelines.interactionPatterns.title': 'Interaction Patterns',
            'product.guidelines.interactionPatterns.subtitle': 'The foundation of our product experience',
            'product.guidelines.interactionPatterns.description': 'We define interaction patterns before any visual design work begins. These patterns establish how users navigate, engage, and accomplish tasks within our products.',
            'product.guidelines.interactionPatterns.intro': 'Interaction patterns are the building blocks of user experience. When designed thoughtfully, they create intuitive and delightful experiences. However, when misused, they can lead to dark patterns that manipulate users or create frustrating experiences.',
            'product.guidelines.interactionPatterns.bestPractices': 'Best Practices',
            'product.guidelines.interactionPatterns.bestPractices.content': '• Always prioritize user needs over business goals\n• Provide clear feedback for every interaction\n• Maintain consistency across all touchpoints\n• Test patterns with real users before implementation\n• Document patterns for team alignment',
            'product.guidelines.interactionPatterns.darkPatterns': 'Dark Patterns to Avoid',
            'product.guidelines.interactionPatterns.darkPatterns.content': '• Hidden costs or subscription traps\n• Misleading button labels or placement\n• Forced continuity without clear opt-out\n• Fake urgency or scarcity tactics\n• Confusing or misleading navigation',
            'product.guidelines.interactionPatterns.onLoad': 'OnLoad (skeleton UI, loading states)',
            'product.guidelines.interactionPatterns.onLoad.description': 'Loading states provide immediate feedback when content is being fetched or processed. Skeleton screens maintain visual continuity and reduce perceived loading time.',
            'product.guidelines.interactionPatterns.onScroll': 'OnScroll (default page vertical scroll as primary interaction)',
            'product.guidelines.interactionPatterns.onScroll.description': 'Vertical scrolling is the most natural interaction for mobile and web. Use it as the primary navigation method, with clear visual cues for scrollable content.',
            'product.guidelines.interactionPatterns.notify': 'Notify (Toast, banner, etc.)',
            'product.guidelines.interactionPatterns.notify.description': 'Non-intrusive notifications that inform users without blocking their workflow. Use for success messages, updates, or gentle reminders.',
            'product.guidelines.interactionPatterns.alert': 'Alert (Toast)',
            'product.guidelines.interactionPatterns.alert.description': 'Urgent notifications that require immediate attention. Use sparingly for critical information, errors, or important confirmations.',
            'product.guidelines.interactionPatterns.pauseAsk': 'Pause & Ask (popup)',
            'product.guidelines.interactionPatterns.pauseAsk.description': 'Modal interactions that pause the current flow to gather information or confirm actions. Use for important decisions that need user attention.',
            'product.guidelines.interactionPatterns.magnify': 'Magnify (bottomsheet)',
            'product.guidelines.interactionPatterns.magnify.description': 'Expandable content that reveals additional information or options. Perfect for mobile interfaces where screen space is limited.',
            'product.guidelines.interactionPatterns.screenToScreen': 'Screen to Screen (navigation patterns)',
            'product.guidelines.interactionPatterns.screenToScreen.description': 'Smooth transitions between different views or screens. Maintain context and provide clear navigation hierarchy.',
            'product.guidelines.interactionPatterns.feedback': 'Feedback (touch, swipe, etc.)',
            'product.guidelines.interactionPatterns.feedback.description': 'Immediate visual or haptic feedback for user interactions. Essential for creating responsive and engaging experiences.',
            'product.guidelines.interactionPatterns.moreToCome': '(more to come)',
            'product.guidelines.interactionPatterns.moreToCome.description': 'Additional patterns will be added as we discover and document new interaction needs.',
            
            'product.guidelines.uiKit.title': 'UI Kit',
            'product.guidelines.uiKit.subtitle': 'Visual components built on interaction foundations',
            'product.guidelines.uiKit.description': 'Our UI components are designed to support the interaction patterns we\'ve established. Every component serves a specific interaction purpose.',
            'product.guidelines.uiKit.atoms': 'Atoms (buttons, inputs, icons)',
            'product.guidelines.uiKit.modules': 'Modules (cards, forms, navigation)',
            'product.guidelines.uiKit.views': 'Views (pages, layouts, screens)',
            
            'product.guidelines.microInteractionPatterns.title': 'Micro-interaction Patterns',
            'product.guidelines.microInteractionPatterns.subtitle': 'Polishing details that bring experiences to life',
            'product.guidelines.microInteractionPatterns.description': 'These subtle details add personality and feedback to our interactions, making the experience feel responsive and delightful.',
            'product.guidelines.microInteractionPatterns.livingIcons': 'Living icons',
            'product.guidelines.microInteractionPatterns.emphasisOn': 'EmphasisOn',
            'product.guidelines.microInteractionPatterns.rewardDelights': 'Reward delights',
            'product.guidelines.microInteractionPatterns.moreToCome': 'More to come',
            
            'product.guidelines.visualPatterns.title': 'Visual Patterns',
            'product.guidelines.visualPatterns.subtitle': 'Connecting product design to brand identity',
            'product.guidelines.visualPatterns.description': 'Visual patterns that ensure our products feel cohesive with our brand while supporting the established interaction patterns.',
            'product.guidelines.visualPatterns.principle1': 'Apply brand colors, typography, and visual elements consistently',
            'product.guidelines.visualPatterns.principle2': 'Create visual hierarchy that supports user task completion',
            'product.guidelines.visualPatterns.principle3': 'Ensure visual patterns work across different screen sizes and contexts',
            'product.guidelines.visualPatterns.principle4': 'Balance brand expression with functional clarity',
            
            'product.guidelines.workflowRituals.title': 'Workflow and Rituals',
            'product.guidelines.workflowRituals.subtitle': 'How design and development work together',
            'product.guidelines.workflowRituals.description': 'The process and tools that ensure our design patterns are properly implemented and maintained across all products.',
            'product.guidelines.workflowRituals.principle1': 'Establish clear handoff processes between design and development',
            'product.guidelines.workflowRituals.principle2': 'Use design tokens to maintain consistency across platforms',
            'product.guidelines.workflowRituals.principle3': 'Implement regular design reviews and quality assurance',
            'product.guidelines.workflowRituals.principle4': 'Document and version control all design system changes',
            
            'product.guidelines.cta.title': 'Ready to implement these guidelines?',
            'product.guidelines.cta.description': 'Access our comprehensive design system resources and start building consistent product experiences.',
            'product.guidelines.cta.button': 'View Resources',
            'product.resources.title': 'Product Resources',
            'product.resources.description': 'Download our design system components, templates, and development resources. Everything you need to build consistent product experiences.',

            'product.principles.alignmentQuestionLabel': 'Alignment question',
            'product.principles.simple.shortTitle': 'Simple',
            'product.principles.simple.title': 'Simple',
            'product.principles.simple.description': 'Designs must be immediately understandable. When there are two ways to do something, choose the simpler one. Users should never need prior knowledge, hidden tricks, or obsessive attention to navigate. Simple means clean, accessible, and predictable. Even with rich interactions or multi-mission flows, the path must stay obvious.',
            'product.principles.simple.alignmentQuestion': 'Could my grandma use this without help?',
            'product.principles.iconic.shortTitle': 'Iconic',
            'product.principles.iconic.title': 'Iconic',
            'product.principles.iconic.description': 'Our work should be distinctive, high-quality, and instantly recognizable. We aim for designs that feel modern, confident, and relevant to our core audience—designs that make other designers quietly jealous. If a screen looks like it could belong to any competitor, it is not finished.',
            'product.principles.iconic.alignmentQuestion': 'Is this something people would share or reference?',
            'product.principles.delightful.shortTitle': 'Delightful',
            'product.principles.delightful.title': 'Delightful',
            'product.principles.delightful.description': 'Interactions should feel enjoyable, not mechanical. Delight is not decoration. It is well-timed motion, playful feedback, and micro-moments that make users feel rewarded and engaged. It must never get in the way of speed or clarity.',
            'product.principles.delightful.alignmentQuestion': 'Is this genuinely fun and engaging?',
            'product.principles.purposeful.shortTitle': 'Purposeful',
            'product.principles.purposeful.title': 'Purposeful',
            'product.principles.purposeful.description': 'Every experience must deliver clear, meaningful value. Time and effort spent by users must be worth it. We operate in a reward-driven ecosystem. Value must be obvious, immediate, and fair. If a flow feels like work, the reward does not justify it, or the benefit is not visible enough, we are wasting everyone\'s time.',
            'product.principles.purposeful.alignmentQuestion': 'Is this worth the user\'s time, or are we just manufacturing effort for no reason?',
            'product.principles.trustworthy.shortTitle': 'Trustworthy',
            'product.principles.trustworthy.title': 'Trustworthy',
            'product.principles.trustworthy.description': 'Users should always feel safe, oriented, and confident, even as they move across funnels. Our experiences span app surfaces, web, and hybrid transitions. The design must stay unified and reliable so users never wonder if they have been dropped into a sketchy third-party zone. Trust comes from consistency, smoothness, tone, and predictable behavior.',
            'product.principles.trustworthy.alignmentQuestion': 'Would a normal user trust this flow from start to finish, or does it feel like we teleported them into a different product?',

            // New submenu items
            'nav.product.uxPatterns': 'UX Patterns',
            'nav.product.visualPatterns': 'Visual Patterns',
            'nav.product.workflowRituals': 'Workflow & Rituals',
            
            // Page-specific translations
            'pages.backToGuidelines': 'Back to Guidelines',
            'pages.sections.interactionPatterns': 'Interaction Patterns',
            'pages.sections.uiKit': 'UI Kit',
            'pages.sections.microInteractions': 'Micro-interactions',
            'pages.sections.designPrinciples': 'Design Principles',
            'pages.sections.visualGuidelines': 'Visual Guidelines',
            'pages.sections.comingSoon': 'Coming Soon',
            'pages.sections.corePrinciples': 'Core Principles',
            'pages.sections.workflowSteps': 'Workflow Steps',
            
            // Interaction Patterns specific
            'interactionPatterns.whileLoading': 'While loading',
            'interactionPatterns.whileLoading.description': 'Skeleton screens, loading states, and progressive disclosure patterns that keep users engaged during wait times.',
            'interactionPatterns.pageScroll': 'Page Scroll',
            'interactionPatterns.pageScroll.description': 'Default vertical scrolling as the primary interaction pattern, with parallax and reveal animations.',
            'interactionPatterns.notify': 'Notify',
            'interactionPatterns.notify.description': 'Toast notifications, banners, and system messages that provide feedback without interrupting user flow.',
            'interactionPatterns.alert': 'Alert',
            'interactionPatterns.alert.description': 'Critical notifications and warnings that require immediate user attention and action.',
            'interactionPatterns.pauseAsk': 'Pause & Ask',
            'interactionPatterns.pauseAsk.description': 'Modal dialogs and popups that pause user flow to gather information or confirm actions.',
            'interactionPatterns.magnify': 'Magnify',
            'interactionPatterns.magnify.description': 'Expandable content and bottom sheets that reveal additional information or options.',
            'interactionPatterns.screenToScreen': 'Screen to Screen',
            'interactionPatterns.screenToScreen.description': 'Smooth transitions between different views or screens with clear navigation hierarchy.',
            'interactionPatterns.feedback': 'Feedback',
            'interactionPatterns.feedback.description': 'Immediate visual or haptic feedback for user interactions to create responsive experiences.',
            'interactionPatterns.moreToCome': 'More to come',
            'interactionPatterns.moreToCome.description': 'Additional patterns will be added as we discover and document new interaction needs.',
            
            // UI Kit specific
            'uiKit.atoms': 'Atoms',
            'uiKit.molecules': 'Molecules',
            'uiKit.organisms': 'Organisms',
            'uiKit.templates': 'Templates',
            'uiKit.pages': 'Pages',
            'uiKit.moreToCome': 'More to come',
            
            // Micro-interactions specific
            'microInteractions.livingIcons': 'Living Icons',
            'microInteractions.emphasisOn': 'Emphasis On',
            'microInteractions.rewardDelights': 'Reward Delights',
            'microInteractions.moreToCome': 'More to come',
            
            // Code preview
            'codePreview.title': 'Code Example',
            'codePreview.copy': 'Copy',
            'codePreview.copied': 'Copied!',
            
            // Live preview
            'livePreview.title': 'Live Preview',
            'livePreview.comingSoon': 'Preview coming soon',
            
            // Footer
            'footer.description': 'Home to Buzzvil\'s design source of truth. We build in the open. This portal is primarily meant to be used internally and by our partners, but we also like anyone to have a look at how we work!',
            'footer.foundations.mission': 'The Mission',
            'footer.foundations.philosophy': 'Our Mindset',
            'footer.foundations.values': 'Working Principles',
            'footer.foundations.team': 'Our Team',
            'footer.foundations.tools': 'Our Stack',
            'footer.brand.principles': 'Principles',
            'footer.brand.guidelines': 'Guidelines',
            'footer.brand.resources': 'Resources',
            'footer.product.principles': 'Principles',
            'footer.product.guidelines': 'Guidelines',
            'footer.product.resources': 'Resources',
            'footer.connect.buzzvil': 'Buzzvil',
            'footer.connect.contact': 'Contact',
            'footer.connect.careers': 'Careers',
            'footer.connect.figma': 'Figma',
            'footer.connect.github': 'GitHub',
            'footer.connect.linkedin': 'LinkedIn',
            'footer.made': 'Made with',
            'footer.by': 'by the Buzzvil Design Team',
            'footer.privacy': 'Privacy Policy',
            'footer.terms': 'Terms of Service',
  },
  ko: {
    // Navigation
    'nav.foundations': '기반',
    'nav.brand': '브랜드',
    'nav.product': '제품',
    'nav.team': '팀',
    'nav.tools': '도구',
    'nav.sections.mission': '미션',
    'nav.sections.philosophy': '마인드셋',
    'nav.sections.values': '작업 원칙',
    'nav.sections.team': '우리의 팀',
    'nav.sections.tools': '우리의 스택',
    
    // Contact Banner
    'banner.title': '커피 한 잔 하며 만나볼까요?',
    'banner.cta': '미팅 예약하기',
    'banner.cta.short': '연락',
    'banner.requirements.schedule': '시간 예약',
    'banner.requirements.info': '정보 포함',
    
    // Hero
    'hero.title': 'Buzzvil Design',
    'hero.subtitle': '매력적인. 재미있는. 확장 가능한.',
    'hero.sentence.start': '우리는 구축합니다',
    'hero.sentence.end': '경험을.',
    'hero.keyword.engaging': '매력적인',
    'hero.keyword.playful': '재미있는',
    'hero.keyword.scalable': '확장 가능한',
            'hero.explore': '기반 탐색',
            'hero.brand': '브랜드',
            'hero.product': '제품',
            'hero.scroll': '스크롤하여 탐색',
    
            // Mission & Vision
            'mission.title': '미션 & 비전',
            'mission.subtitle': '버즈빌에서 우리가 하는 모든 일을 이끄는 미션과 비전.',
            'mission.mission.title': '미션',
            'mission.mission.subtitle': '지금 우리가 하는 일',
            'mission.mission.content': '우리는 사람들이 버즈빌의 광고 캠페인과 브랜드를 발견하고, 경험하고, 지속적으로 참여하는 방식을 형성하는 의미 있는 상호작용을 디자인합니다. 우리의 작업은 광고를 사람들이 탐험하고 싶어하는 경험으로 바꾸며, 주의를 끌고, 호기심을 자극하며, 광고주에게 성과를 가져다주는 순간들을 만듭니다.',
            'mission.vision.title': '비전',
            'mission.vision.subtitle': '우리가 구축하는 미래',
            'mission.vision.content': '우리는 광고 캠페인과 브랜드 경험을 사용자와 광고주를 연결하는 매력적이고 반복 가능한 상호작용으로 변화시켜 AdTech 디자인의 새로운 표준을 제시합니다. 이러한 새로운 참여 방식을 통해, 버즈빌은 광고가 즐겁고, 사람들의 일상 경험에 자연스럽게 통합되는 미래를 이끕니다.',
    
            // Philosophy
            'philosophy.title': '철학',
            'philosophy.subtitle': '우리가 접근하는 방식',
            'philosophy.content': '버즈빌에서 디자인은 사람들이 광고를 경험하는 방식을 형성합니다. 방해가 아닌 즐거운 연결의 순간으로 말입니다. 우리는 브랜드 접점부터 제품 내 경험까지 모든 상호작용이 재미있고, 매력적이며, 자연스러워야 한다고 믿습니다. 우리의 역할은 버즈빌이 생태계 전반에서 어떻게 보이고, 느껴지고, 행동하는지를 통합하여 캠페인과 플랫폼을 하나의 일관되고 즐거운 경험으로 만드는 것입니다. 우리의 원칙과 원팀 정신에 이끌려, 우리는 신뢰를 영감하고, 성과를 추진하며, AdTech가 될 수 있는 새로운 표준을 설정하기 위해 디자인합니다.',
    
            // Ways of Working
            'waysOfWorking.title': '작업 방식',
            'waysOfWorking.subtitle': '버즈빌 디자인에서 우리가 생각하고, 창조하고, 협업하는 방식.',
            'waysOfWorking.principles.title': '우리의 원칙',
            'waysOfWorking.principles.subtitle': '버즈빌에서 디자인하기 위해 함께 작업하는 방식.',
            'waysOfWorking.team.title': '우리의 팀',
            'waysOfWorking.team.subtitle': '버즈빌 디자인을 만드는 사람들.',
            'waysOfWorking.stack.title': '우리의 스택',
            'waysOfWorking.stack.subtitle': '우리의 디자인 작업을 지원하는 도구들.',
    
    // Principles
    'principles.title': '원칙',
    'principles.subtitle': '디자인과 개발 접근 방식을 이끄는 원칙들.',
    'principles.reward.title': '보상 = 시간',
    'principles.reward.shortTitle': '보상',
    'principles.reward.content': '보상은 사용자 주의의 투명하고 측정 가능한 교환입니다. 메커니즘: 1P ≈ 1초의 주의. 이는 사용자에게 일관성을, 광고주에게 예측 가능성을 제공합니다.',
    'principles.delight.title': '기만 없는 기쁨',
    'principles.delight.shortTitle': '기쁨',
    'principles.delight.content': '보상은 동기를 불러일으키지만, 경험이 참여를 지속시킵니다. 우리는 절대 다크 패턴을 사용하지 않습니다: 광고를 다른 광고 위에 겹치지 않고, 오해를 불러일으키지 않으며, 함정에 빠뜨리지 않습니다. 상호작용은 재미있고 명확하며 존중스러워야 합니다.',
    'principles.scalable.title': '디자인으로 확장 가능하게',
    'principles.scalable.shortTitle': '확장성',
    'principles.scalable.content': '모든 디자인 결정은 제품, 파트너, 비즈니스 모델에 걸쳐 확장되어야 합니다. 우리는 의미 있는 맞춤화를 제공하지만 지속 불가능한 예외는 피합니다. 이러한 원칙은 시스템을 분할하는 비즈니스나 제품 결정을 거부할 수 있습니다.',
    
    // Principles Characteristics
    'principles.reward.characteristics.0': '투명한 교환',
    'principles.reward.characteristics.1': '측정 가능한 주의',
    'principles.reward.characteristics.2': '사용자 일관성',
    'principles.reward.characteristics.3': '광고주 예측 가능성',
    'principles.delight.characteristics.0': '다크 패턴 없음',
    'principles.delight.characteristics.1': '재미있는 상호작용',
    'principles.delight.characteristics.2': '명확한 소통',
    'principles.delight.characteristics.3': '존중스러운 디자인',
    'principles.scalable.characteristics.0': '크로스 제품 확장',
    'principles.scalable.characteristics.1': '의미 있는 맞춤화',
    'principles.scalable.characteristics.2': '시스템 무결성',
    'principles.scalable.characteristics.3': '결정 거부 권한',
    
    // Values
    'values.title': '작업 원칙',
    'values.subtitle': '버즈빌에서 디자인하기 위해 함께 작업하는 방식.',
    'values.build.title': '열린 공간에서 구축',
    'values.build.shortTitle': '열린 공간에서 구축',
    'values.build.content': '우리는 거칠게 시작하고, 일찍 공유하며, 빠르게 반복합니다. 모든 디자이너는 탐색을 가속화하는 AI 도구에 접근할 수 있습니다. 피드백과 빠른 루프는 아이디어를 견고하고 프로덕션 준비된 솔루션으로 정제하는 데 도움이 됩니다.',
    'values.build.tagline': '빠르게 반복하라.',
    'values.clarity.title': '피드백을 통한 명확성',
    'values.clarity.shortTitle': '명확하게',
    'values.clarity.content': '우리는 솔직하고 정확하게 소통합니다. 피드백은 우리가 성장하는 방법입니다: 명확하게 주고, 열린 마음으로 받고, 건설적으로 적용합니다. 명확한 소통은 신뢰를 구축하고 낭비된 노력을 피합니다.',
    'values.clarity.tagline': '명확성을 먼저, 피드백은 항상.',
    'values.grit.title': '소유하고, 출시하라',
    'values.grit.shortTitle': '소유하고, 출시하라',
    'values.grit.content': '디자이너는 단순히 초안에서 멈추지 않습니다. 우리는 사용자 스토리와 프로젝트의 소유권을 가지고, 첫 스케치부터 프로덕션까지 밀어붙입니다. 우리는 결과가 실제가 될 때까지 끈기와 기술로 이끕니다.',
    'values.grit.tagline': '그릿.',
    'values.explore.title': '대담한 탐험가',
    'values.explore.shortTitle': '탐험가',
    'values.explore.content': '우리는 연구, 실험, AI 채택을 우리 기술의 핵심으로 받아들입니다. 강력한 도구와 탐구 문화를 가지고, 넓게 탐색하고, 엄격하게 검증하고, 자신감 있게 디자인하지 않을 변명이 없습니다.',
    'values.explore.tagline': '대담하게 탐험하고, 깊이 연구하라.',
    'values.team.title': 'One-UX',
    'values.team.shortTitle': 'One-UX',
    'values.team.content': '우리는 확장하기 전에 디자인 팀으로 정렬합니다. 이는 자주 동기화하고, 관례를 공유하고, 일관된 관행을 적용하는 것을 의미합니다. 우리의 정렬은 파트너, 사용자, 광고주가 버즈빌 디자인을 하나의 일관된 시스템으로 경험하도록 보장합니다.',
    'values.team.tagline': '먼저 정렬하고, 함께 확장하라.',
    
    // Values Characteristics
    'values.build.characteristics.0': '빠른 프로토타이핑',
    'values.build.characteristics.1': 'AI 기반 탐색',
    'values.build.characteristics.2': '조기 공유',
    'values.build.characteristics.3': '빠른 반복',
    'values.clarity.characteristics.0': '솔직함과 정확성',
    'values.clarity.characteristics.1': '열린 소통',
    'values.clarity.characteristics.2': '건설적 성장',
    'values.clarity.characteristics.3': '신뢰 구축',
    'values.grit.characteristics.0': '완전한 소유권',
    'values.grit.characteristics.1': '끝까지 배송',
    'values.grit.characteristics.2': '끈기',
    'values.grit.characteristics.3': '프로덕션 집중',
    'values.explore.characteristics.0': '연구 중심',
    'values.explore.characteristics.1': 'AI 채택',
    'values.explore.characteristics.2': '넓은 탐색',
    'values.explore.characteristics.3': '엄격한 검증',
    'values.team.characteristics.0': '팀 정렬',
    'values.team.characteristics.1': '공유된 관례',
    'values.team.characteristics.2': '일관된 관행',
    'values.team.characteristics.3': '일관된 시스템',
    
    // Resources
    'resources.title': '디자인 리소스',
    'resources.subtitle': '탁월한 사용자 경험을 만들기 위해 필요한 모든 것. 최신 디자인 파일, 가이드라인, 템플릿을 다운로드하세요.',
    'resources.category.design-system': '디자인 시스템',
    'resources.category.templates-patterns': '템플릿 & 패턴',
    'resources.category.brand-assets': '브랜드 & 자산',
    
    // Team
    'team.title': '우리 디자인 팀을 만나보세요',
    'team.subtitle': '탁월한 사용자 경험을 만들고 디자인 우수성을 추진하기 위해 함께 일하는 다양한 창의적 마음의 그룹.',
    
    // Tools
    'tools.title': '우리의 스택',
    'tools.subtitle': '우리의 디자인 작업을 지원하는 도구들.',
    'tools.visit': '도구 방문',
    'tools.category.design-development': '디자인 & 개발 도구',
    
            // Brand
            'brand.sections.principles': '원칙',
            'brand.sections.guidelines': '가이드라인',
            'brand.sections.resources': '리소스',
            'brand.intro.catchphrase': '모든 접점에서 버즈빌이 어떻게 보이고, 느껴지고, 행동하는지를 형성합니다.',
            'brand.principles.title': '브랜드 원칙',
            'brand.principles.description': '모든 결정, 상호작용, 우리가 만드는 경험을 이끄는 핵심 브랜드 원칙들. 이러한 근본적인 가치들은 모든 접점에서 일관성과 진정성을 보장합니다.',
            'brand.guidelines.title': '브랜드 가이드라인',
            'brand.guidelines.description': '모든 플랫폼과 접점에서 브랜드를 일관되게 적용하기 위한 포괄적인 가이드라인. 로고 사용법부터 색상 팔레트, 타이포그래피, 톤앤매너까지.',
            'brand.resources.title': '브랜드 리소스',
            'brand.resources.description': '브랜드 자산, 템플릿, 리소스를 다운로드하세요. 프로젝트와 캠페인에서 브랜드를 일관되게 구현하는 데 필요한 모든 것.',
            
            // Brand guidelines (Identity System 2.0)
            'brand.hero.tag': '아이덴티티 시스템 26.1',
            'brand.hero.title': '차분하고 상징적. 항상 맥락 속에.',
            'brand.hero.description': '제품 행동 위에 구축된 우리의 브랜드는 맥락에 적합합니다. 어우러질 때는 차분하게, 명확함이 필요할 때는 상징적으로.',
            'brand.hero.cta': '가이드라인 살펴보기',
            'brand.nav.logo': '로고',
            'brand.nav.colors': '색상',
            'brand.nav.typography': '타이포그래피',
            'brand.nav.imagery': '이미지',
            'brand.nav.downloads': '다운로드',
            'brand.logo.title': '카멜레온 (The Chameleon)',
            'brand.logo.description': '로고는 카멜레온과 같습니다. 배경에 따라 검은색 또는 흰색으로 적응합니다. 파트너 맥락에서 주색상이나 보조 색상을 사용할 수 있지만, 깨끗한 브랜드 미학을 유지하기 위해 흑백 사용을 권장합니다.',
            'brand.logo.lightBg': '밝은 배경',
            'brand.logo.darkBg': '어두운 배경',
            'brand.logo.partnerContext': '파트너 맥락 예시',
            'brand.logo.kakaoBank': '카카오뱅크',
            'brand.logo.kBank': '케이뱅크',
            'brand.logo.oliveYoung': '올리브영',
            'brand.logo.clearspace': '여백 (Clearspace)',
            'brand.logo.clearspaceDesc': '가독성과 임팩트를 위해 항상 로고 주변에 충분한 여백을 유지하세요.',
            'brand.logo.unacceptable': '잘못된 사용 예',
            'brand.logo.unacceptableDesc': '브랜드 일관성을 유지하기 위해, 가독성이나 형태를 훼손하는 변형은 피해주세요.',
            'brand.logo.noStretch': '늘리지 마세요',
            'brand.logo.noCrop': '자르지 마세요',
            'brand.logo.noRotate': '회전하지 마세요',
            'brand.logo.noDeform': '변형하지 마세요',
            'brand.logo.logoTreatment': '로고 트리트먼트',
            'brand.logo.maskingTitle': '마스킹 (이미지 및 비디오)',
            'brand.logo.maskingDesc': '카멜레온 철학의 일환으로, 로고 형태 내부에 이미지, 일러스트레이션 또는 비디오를 삽입하는 것을 허용합니다. 배경과 충분한 대비를 유지하세요.',
            'brand.logo.threeDTitle': '3D 가이드라인',
            'brand.logo.threeDDesc': '깊이감을 더하기 위한 아이소메트릭 3D 변형은 허용됩니다. 미학은 추상적이고 단순하며 톤이 맞아야 합니다. 자유형 3D 왜곡은 피하세요.',
            'brand.logo.isometricLabel': '아이소메트릭 (허용됨)',
            'brand.logo.freeformLabel': '자유형 3D (허용되지 않음)',
            'brand.colors.grayscale': '그레이스케일',
            'brand.colors.grayscaleDesc': '우리의 주 팔레트입니다. 거의 검은색과 흰색만을 사용하여 높은 대비와 깨끗한 룩을 지향합니다.',
            'brand.colors.red': '강조색 레드',
            'brand.colors.redDesc': '주요 동작이나 중요한 알림에 제한적으로 사용하세요. 전체 구성의 10% 미만으로 사용하는 것을 목표로 하세요.',
            'brand.colors.orange': '강조색 오렌지',
            'brand.colors.orangeDesc': '빨간색을 보완하는 보조 강조색입니다. 배너나 하이라이트에 사용하세요.',
            'brand.colors.copied': '복사됨!',
            'brand.typography.primaryTitle': '주요 서체: Pretendard / Inter',
            'brand.typography.primaryDesc': '한국어는 Pretendard, 라틴은 Inter. 깔끔함, 가독성, 현대적인 미학을 위한 주요 서체입니다. 제목과 본문 모두에 적합합니다.',
            'brand.typography.h1Meta': 'Heading 1 / Bold / 48px',
            'brand.typography.h1Text': '효과적인 광고',
            'brand.typography.h2Meta': 'Heading 2 / Semibold / 36px',
            'brand.typography.h2Text': '사용자 혜택과 광고주 성공이 만나는 곳',
            'brand.typography.bodyMeta': 'Body / Regular / 16px',
            'brand.typography.bodyText': '우리의 로고는 카멜레온입니다. 고객이나 파트너의 어떤 색상이든 취할 수 있습니다. 기본적으로는 배경에 따라 흑백을 취합니다.',
            'brand.typography.heroTitle': '디스플레이 서체: Nunito (영문 전용)',
            'brand.typography.heroDesc': '영문 전용 서체. 네비게이션, 히어로 헤드라인, 임팩트 있는 디스플레이 텍스트에 사용합니다. 둥글고 친근한 인상을 줍니다.',
            'brand.typography.heroMeta': '헤더 / Extrabold / 36px',
            'brand.typography.secondaryTitle': '보조 서체: 나눔고딕코딩 / Anonymous Pro',
            'brand.typography.secondaryDesc': '기술적 뿌리를 강조하기 위한 고정폭 서체. 한국어는 나눔고딕코딩, 라틴은 Anonymous Pro. 키커, 라벨, 숫자, 코드 조각 또는 기술 데이터에 사용하세요.',
            'brand.typography.kickerMeta': 'Kicker / Bold / 14px',
            'brand.typography.kickerText': '프로덕트 백엔드 팀',
            'brand.typography.dataMeta': 'Data / Regular / 14px',
            'brand.imagery.title': '룩 앤 필',
            'brand.imagery.description': '우리의 비주얼은 기술적이고 세련되며 어두운 테마를 지향합니다. 데이터와 인프라를 표현하기 위해 3D 추상 요소를 사용합니다.',
            'brand.imagery.visualIdentity': '비주얼 아이덴티티 적용',
            'brand.imagery.webInterface': '웹 인터페이스',
            'brand.downloads.logoGenerator': '로고 생성기',
            'brand.downloads.logoGeneratorDesc': '공식 브랜드 자산을 커스터마이징하고 다운로드하세요. 타입을 선택하고 색상을 고른 뒤 고해상도 PNG를 받으세요.',
            'brand.downloads.iconGenerator': '아이콘 생성기',
            'brand.downloads.iconGeneratorDesc': '일관된 아이콘을 검색하고 생성하세요. 리워드, 포인트, 게임 관련 인터페이스에 최적화되어 있습니다.',
            'brand.downloads.isometricGenerator': '아이소메트릭 생성기',
            'brand.downloads.isometricGeneratorDesc': '로고 마크의 3D 아이소메트릭 버전을 생성합니다. 각도와 원근감을 조정하여 구성에 맞게 사용하세요.',
            'brand.downloads.comingSoon': '곧 출시',
            'brand.logoGenerator.title': '로고 생성기',
            'brand.logoGenerator.description': '공식 브랜드 자산을 커스터마이징하고 다운로드하세요. 타입을 선택하고 색상을 고른 뒤 고해상도 PNG를 받으세요.',
            'brand.logoGenerator.assetType': '자산 유형',
            'brand.logoGenerator.mark': '로고 마크',
            'brand.logoGenerator.wordmark': '워드마크',
            'brand.logoGenerator.color': '색상',
            'brand.logoGenerator.customHex': '커스텀 헥스',
            'brand.logoGenerator.download': 'PNG 다운로드 (512px 높이)',
            'brand.iconGenerator.title': '아이콘 생성기',
            'brand.iconGenerator.description': '일관된 아이콘을 검색하고 생성하세요. 리워드, 포인트, 게임 관련 인터페이스에 최적화되어 있습니다.',
            'brand.iconGenerator.searchLabel': '라이브러리 검색',
            'brand.iconGenerator.searchPlaceholder': '아이콘 검색 (예: Calendar, User, Gift...)',
            'brand.iconGenerator.results': '결과',
            'brand.iconGenerator.popular': '인기 아이콘',
            'brand.iconGenerator.noResults': '"{query}"에 대한 아이콘을 찾을 수 없습니다',
            'brand.iconGenerator.loadMore': '더 보기',
            'brand.iconGenerator.weight': '굵기',
            'brand.iconGenerator.color': '색상',
            'brand.iconGenerator.customHex': '커스텀 헥스',
            'brand.iconGenerator.download': 'PNG 다운로드',
            'brand.iconGenerator.preview': '미리보기',
            'brand.isometricGenerator.title': '아이소메트릭 투영',
            'brand.isometricGenerator.description': '로고 마크의 정사영 아이소메트릭 투영을 생성합니다. 결과물은 브랜드에 안전하고, 반복 가능하며, 작은 크기에서도 선명합니다.',
            'brand.isometricGenerator.angle': '각도',
            'brand.isometricGenerator.direction': '방향',
            'brand.isometricGenerator.download': 'PNG 다운로드 (512px)',
            'brand.isometricGenerator.angleSubtle': '은은함',
            'brand.isometricGenerator.angleStandard': '표준',
            'brand.isometricGenerator.angleStrong': '강함',
            'brand.isometricGenerator.dirLeft': '왼쪽',
            'brand.isometricGenerator.dirCenter': '가운데',
            'brand.isometricGenerator.dirRight': '오른쪽',
            'brand.isometricGenerator.color': '색상',
            'brand.isometricGenerator.customHex': '커스텀',
            'brand.isometricGenerator.dirTopRight': '우측 상단',
            'brand.isometricGenerator.dirTopLeft': '좌측 상단',
            'brand.isometricGenerator.dirBottomRight': '우측 하단',
            'brand.isometricGenerator.dirBottomLeft': '좌측 하단',
            'brand.isometricGenerator.depth': '깊이',
            'brand.isometricGenerator.depthHint': '마크의 치수 오프셋을 조절합니다.',
            'brand.isometricGenerator.edgeStyle': '엣지 스타일',
            'brand.isometricGenerator.edgeSharp': '샤프',
            'brand.isometricGenerator.edgeSoft': '소프트',
            'brand.isometricGenerator.edgeOutline': '아웃라인만',
            'brand.isometricGenerator.faceColor': '면 색상 모드',
            'brand.isometricGenerator.faceFlat': '플랫',
            'brand.isometricGenerator.faceSubtle': '은은한 음영',
            'brand.isometricGenerator.faceStroke': '스트로크만',
            'brand.isometricGenerator.brandSafe': '브랜드 안전',
            
            // Product
            'product.sections.principles': '원칙',
            'product.sections.guidelines': '가이드라인',
            'product.sections.resources': '리소스',
            'product.intro.catchphrase': '사용자가 참여하고 싶어하는 즐거운 경험을 디자인합니다.',
            'product.guidelines.title': '제품 가이드라인',
            'product.guidelines.intro': '우리의 제품 경험은 상호작용을 중심으로 회전하며, 이는 모든 경험의 핵심 속성입니다. UI 키트를 작성하기 전에 먼저 상호작용 패턴을 정의합니다. 그 다음 UI 키트 위에 마이크로 상호작용과 같은 세부 사항을 다듬습니다.',
            
            'product.guidelines.uxPatterns.title': 'UX 패턴',
            'product.guidelines.uxPatterns.description': '사용자가 우리 제품과 상호작용하는 방식을 정의하는 핵심 사용자 경험 패턴입니다. 이러한 패턴은 시각적 디자인 작업을 시작하기 전에 설정됩니다.',
            
            'product.guidelines.interactionPatterns.title': '상호작용 패턴',
            'product.guidelines.interactionPatterns.subtitle': '제품 경험의 기초',
            'product.guidelines.interactionPatterns.description': '시각적 디자인 작업을 시작하기 전에 상호작용 패턴을 정의합니다. 이러한 패턴은 사용자가 제품 내에서 탐색하고 참여하며 작업을 완료하는 방법을 설정합니다.',
            'product.guidelines.interactionPatterns.intro': '상호작용 패턴은 사용자 경험의 구성 요소입니다. 신중하게 설계되면 직관적이고 즐거운 경험을 만들지만, 잘못 사용되면 사용자를 조작하거나 좌절스러운 경험을 만드는 다크 패턴으로 이어질 수 있습니다.',
            'product.guidelines.interactionPatterns.bestPractices': '모범 사례',
            'product.guidelines.interactionPatterns.bestPractices.content': '• 항상 비즈니스 목표보다 사용자 요구를 우선시\n• 모든 상호작용에 대한 명확한 피드백 제공\n• 모든 터치포인트에서 일관성 유지\n• 구현 전에 실제 사용자와 패턴 테스트\n• 팀 정렬을 위한 패턴 문서화',
            'product.guidelines.interactionPatterns.darkPatterns': '피해야 할 다크 패턴',
            'product.guidelines.interactionPatterns.darkPatterns.content': '• 숨겨진 비용 또는 구독 함정\n• 오해의 소지가 있는 버튼 라벨이나 배치\n• 명확한 옵트아웃 없이 강제 연속성\n• 가짜 긴급성이나 희소성 전술\n• 혼란스럽거나 오해의 소지가 있는 네비게이션',
            'product.guidelines.interactionPatterns.onLoad': 'OnLoad (스켈레톤 UI, 로딩 상태)',
            'product.guidelines.interactionPatterns.onLoad.description': '로딩 상태는 콘텐츠가 가져오거나 처리될 때 즉각적인 피드백을 제공합니다. 스켈레톤 화면은 시각적 연속성을 유지하고 인지된 로딩 시간을 줄입니다.',
            'product.guidelines.interactionPatterns.onScroll': 'OnScroll (기본 페이지 세로 스크롤을 주요 상호작용으로)',
            'product.guidelines.interactionPatterns.onScroll.description': '세로 스크롤은 모바일과 웹에서 가장 자연스러운 상호작용입니다. 이를 주요 네비게이션 방법으로 사용하고, 스크롤 가능한 콘텐츠에 대한 명확한 시각적 단서를 제공하세요.',
            'product.guidelines.interactionPatterns.notify': 'Notify (토스트, 배너 등)',
            'product.guidelines.interactionPatterns.notify.description': '사용자의 워크플로우를 차단하지 않고 정보를 제공하는 비침습적 알림입니다. 성공 메시지, 업데이트 또는 부드러운 알림에 사용하세요.',
            'product.guidelines.interactionPatterns.alert': 'Alert (토스트)',
            'product.guidelines.interactionPatterns.alert.description': '즉각적인 주의가 필요한 긴급 알림입니다. 중요한 정보, 오류 또는 중요한 확인에만 사용하세요.',
            'product.guidelines.interactionPatterns.pauseAsk': 'Pause & Ask (팝업)',
            'product.guidelines.interactionPatterns.pauseAsk.description': '현재 플로우를 일시 중지하여 정보를 수집하거나 작업을 확인하는 모달 상호작용입니다. 사용자의 주의가 필요한 중요한 결정에 사용하세요.',
            'product.guidelines.interactionPatterns.magnify': 'Magnify (바텀시트)',
            'product.guidelines.interactionPatterns.magnify.description': '추가 정보나 옵션을 보여주는 확장 가능한 콘텐츠입니다. 화면 공간이 제한적인 모바일 인터페이스에 완벽합니다.',
            'product.guidelines.interactionPatterns.screenToScreen': 'Screen to Screen (네비게이션 패턴)',
            'product.guidelines.interactionPatterns.screenToScreen.description': '다른 뷰나 화면 간의 부드러운 전환입니다. 컨텍스트를 유지하고 명확한 네비게이션 계층을 제공하세요.',
            'product.guidelines.interactionPatterns.feedback': 'Feedback (터치, 스와이프 등)',
            'product.guidelines.interactionPatterns.feedback.description': '사용자 상호작용에 대한 즉각적인 시각적 또는 햅틱 피드백입니다. 반응적이고 매력적인 경험을 만드는 데 필수적입니다.',
            'product.guidelines.interactionPatterns.moreToCome': '(더 많은 패턴 예정)',
            'product.guidelines.interactionPatterns.moreToCome.description': '새로운 상호작용 요구를 발견하고 문서화함에 따라 추가 패턴이 추가될 예정입니다.',
            
            'product.guidelines.uiKit.title': 'UI 키트',
            'product.guidelines.uiKit.subtitle': '상호작용 기반 위에 구축된 시각적 컴포넌트',
            'product.guidelines.uiKit.description': '우리의 UI 컴포넌트는 우리가 설정한 상호작용 패턴을 지원하도록 설계되었습니다. 모든 컴포넌트는 특정한 상호작용 목적을 제공합니다.',
            'product.guidelines.uiKit.atoms': 'Atoms (버튼, 입력, 아이콘)',
            'product.guidelines.uiKit.modules': 'Modules (카드, 폼, 네비게이션)',
            'product.guidelines.uiKit.views': 'Views (페이지, 레이아웃, 화면)',
            
            'product.guidelines.microInteractionPatterns.title': '마이크로 상호작용 패턴',
            'product.guidelines.microInteractionPatterns.subtitle': '경험을 생생하게 만드는 세부 사항',
            'product.guidelines.microInteractionPatterns.description': '이러한 미묘한 세부 사항은 우리의 상호작용에 개성과 피드백을 추가하여 경험이 반응적이고 즐겁게 느껴지도록 합니다.',
            'product.guidelines.microInteractionPatterns.livingIcons': 'Living icons',
            'product.guidelines.microInteractionPatterns.emphasisOn': 'EmphasisOn',
            'product.guidelines.microInteractionPatterns.rewardDelights': 'Reward delights',
            'product.guidelines.microInteractionPatterns.moreToCome': 'More to come',
            
            'product.guidelines.visualPatterns.title': '시각적 패턴',
            'product.guidelines.visualPatterns.subtitle': '제품 디자인을 브랜드 아이덴티티와 연결',
            'product.guidelines.visualPatterns.description': '제품이 우리 브랜드와 일관성을 느끼면서도 설정된 상호작용 패턴을 지원하도록 하는 시각적 패턴입니다.',
            'product.guidelines.visualPatterns.principle1': '브랜드 색상, 타이포그래피, 시각적 요소를 일관되게 적용',
            'product.guidelines.visualPatterns.principle2': '사용자 작업 완료를 지원하는 시각적 계층 구조 생성',
            'product.guidelines.visualPatterns.principle3': '다양한 화면 크기와 컨텍스트에서 시각적 패턴이 작동하도록 보장',
            'product.guidelines.visualPatterns.principle4': '브랜드 표현과 기능적 명확성의 균형 유지',
            
            'product.guidelines.workflowRituals.title': '워크플로우와 의식',
            'product.guidelines.workflowRituals.subtitle': '디자인과 개발이 함께 작업하는 방식',
            'product.guidelines.workflowRituals.description': '우리의 디자인 패턴이 모든 제품에서 적절히 구현되고 유지되도록 하는 프로세스와 도구입니다.',
            'product.guidelines.workflowRituals.principle1': '디자인과 개발 간의 명확한 인수인계 프로세스 수립',
            'product.guidelines.workflowRituals.principle2': '플랫폼 간 일관성을 유지하기 위해 디자인 토큰 사용',
            'product.guidelines.workflowRituals.principle3': '정기적인 디자인 리뷰와 품질 보증 구현',
            'product.guidelines.workflowRituals.principle4': '모든 디자인 시스템 변경사항 문서화 및 버전 관리',
            
            'product.guidelines.cta.title': '이 가이드라인을 구현할 준비가 되셨나요?',
            'product.guidelines.cta.description': '포괄적인 디자인 시스템 리소스에 액세스하고 일관된 제품 경험 구축을 시작하세요.',
            'product.guidelines.cta.button': '리소스 보기',
            'product.resources.title': '제품 리소스',
            'product.resources.description': '디자인 시스템 컴포넌트, 템플릿, 개발 리소스를 다운로드하세요. 일관된 제품 경험을 구축하는 데 필요한 모든 것.',

            'product.principles.alignmentQuestionLabel': '정렬 질문',
            'product.principles.simple.shortTitle': '심플',
            'product.principles.simple.title': 'Simple',
            'product.principles.simple.description': '디자인은 즉시 이해 가능해야 합니다. 두 가지 방법이 있다면 더 단순한 것을 선택합니다. 사용자는 사전 지식, 숨겨진 비결, 또는 집중적인 주의 없이 탐색할 수 있어야 합니다. 심플함은 깔끔함, 접근성, 예측 가능성을 의미합니다. 풍부한 상호작용이나 다중 미션 흐름에서도 경로는 명확해야 합니다.',
            'product.principles.simple.alignmentQuestion': '할머니도 도움 없이 사용할 수 있을까요?',
            'product.principles.iconic.shortTitle': '아이코닉',
            'product.principles.iconic.title': 'Iconic',
            'product.principles.iconic.description': '우리 작업은 독특하고, 고품질이며, 즉시 인식 가능해야 합니다. 핵심 대상에게 현대적이고 자신감 있고 관련성 있게 느껴지는 디자인을 목표로 합니다. 화면이 어떤 경쟁사 제품에 속한 것처럼 보인다면, 아직 완성되지 않은 것입니다.',
            'product.principles.iconic.alignmentQuestion': '사람들이 공유하거나 참조할 만한 것일까요?',
            'product.principles.delightful.shortTitle': '딜라이트풀',
            'product.principles.delightful.title': 'Delightful',
            'product.principles.delightful.description': '상호작용은 기계적이 아닌 즐거움을 주어야 합니다. 딜라이트는 장식이 아닙니다. 적절한 타이밍의 모션, 재미있는 피드백, 사용자를 보상받고 참여한다고 느끼게 하는 순간들입니다. 속도나 명확성을 방해해서는 안 됩니다.',
            'product.principles.delightful.alignmentQuestion': '진정으로 재미있고 참여를 유도할까요?',
            'product.principles.purposeful.shortTitle': '퍼포스풀',
            'product.principles.purposeful.title': 'Purposeful',
            'product.principles.purposeful.description': '모든 경험은 명확하고 의미 있는 가치를 전달해야 합니다. 사용자가 투자하는 시간과 노력이 가치 있어야 합니다. 보상 중심 생태계에서 가치는 명확하고, 즉각적이며, 공정해야 합니다. 흐름이 일처럼 느껴지거나, 보상이 정당화되지 않거나, 혜택이 충분히 보이지 않는다면 우리는 모두의 시간을 낭비하는 것입니다.',
            'product.principles.purposeful.alignmentQuestion': '사용자의 시간에 가치가 있나요, 아니면 이유 없이 노력을 만드는 건가요?',
            'product.principles.trustworthy.shortTitle': '트러스트워디',
            'product.principles.trustworthy.title': 'Trustworthy',
            'product.principles.trustworthy.description': '사용자는 퍼널을 이동해도 항상 안전하고, 방향을 알고, 자신감을 느껴야 합니다. 우리 경험은 앱, 웹, 하이브리드 전환에 걸쳐 있습니다. 디자인은 통합되고 안정적이어야 사용자가 의심스러운 서드파티 영역에 떨어졌는지 궁금해하지 않습니다. 신뢰는 일관성, 부드러움, 톤, 예측 가능한 행동에서 옵니다.',
            'product.principles.trustworthy.alignmentQuestion': '일반 사용자가 처음부터 끝까지 이 흐름을 신뢰할 수 있을까요, 아니면 다른 제품으로 순간이동한 것처럼 느껴지나요?',

            // New submenu items
            'nav.product.uxPatterns': 'UX 패턴',
            'nav.product.visualPatterns': '시각적 패턴',
            'nav.product.workflowRituals': '워크플로우 & 의식',
            
            // Page-specific translations
            'pages.backToGuidelines': '가이드라인으로 돌아가기',
            'pages.sections.interactionPatterns': '상호작용 패턴',
            'pages.sections.uiKit': 'UI 키트',
            'pages.sections.microInteractions': '마이크로 상호작용',
            'pages.sections.designPrinciples': '디자인 원칙',
            'pages.sections.visualGuidelines': '시각적 가이드라인',
            'pages.sections.comingSoon': '곧 출시',
            'pages.sections.corePrinciples': '핵심 원칙',
            'pages.sections.workflowSteps': '워크플로우 단계',
            
            // Interaction Patterns specific
            'interactionPatterns.whileLoading': '로딩 중',
            'interactionPatterns.whileLoading.description': '사용자가 대기하는 동안 참여를 유지하는 스켈레톤 화면, 로딩 상태, 점진적 공개 패턴입니다.',
            'interactionPatterns.pageScroll': '페이지 스크롤',
            'interactionPatterns.pageScroll.description': '패럴랙스와 공개 애니메이션을 포함한 주요 상호작용 패턴으로서의 기본 세로 스크롤입니다.',
            'interactionPatterns.notify': '알림',
            'interactionPatterns.notify.description': '사용자 플로우를 방해하지 않고 피드백을 제공하는 토스트 알림, 배너, 시스템 메시지입니다.',
            'interactionPatterns.alert': '경고',
            'interactionPatterns.alert.description': '즉각적인 사용자 주의와 조치가 필요한 중요한 알림과 경고입니다.',
            'interactionPatterns.pauseAsk': '일시정지 & 질문',
            'interactionPatterns.pauseAsk.description': '정보를 수집하거나 작업을 확인하기 위해 사용자 플로우를 일시 중지하는 모달 대화상자와 팝업입니다.',
            'interactionPatterns.magnify': '확대',
            'interactionPatterns.magnify.description': '추가 정보나 옵션을 보여주는 확장 가능한 콘텐츠와 바텀시트입니다.',
            'interactionPatterns.screenToScreen': '화면 간 이동',
            'interactionPatterns.screenToScreen.description': '명확한 네비게이션 계층을 가진 다른 뷰나 화면 간의 부드러운 전환입니다.',
            'interactionPatterns.feedback': '피드백',
            'interactionPatterns.feedback.description': '반응적인 경험을 만들기 위한 사용자 상호작용에 대한 즉각적인 시각적 또는 햅틱 피드백입니다.',
            'interactionPatterns.moreToCome': '더 많은 패턴 예정',
            'interactionPatterns.moreToCome.description': '새로운 상호작용 요구를 발견하고 문서화함에 따라 추가 패턴이 추가될 예정입니다.',
            
            // UI Kit specific
            'uiKit.atoms': '원자',
            'uiKit.molecules': '분자',
            'uiKit.organisms': '유기체',
            'uiKit.templates': '템플릿',
            'uiKit.pages': '페이지',
            'uiKit.moreToCome': '더 많은 컴포넌트 예정',
            
            // Micro-interactions specific
            'microInteractions.livingIcons': '살아있는 아이콘',
            'microInteractions.emphasisOn': '강조',
            'microInteractions.rewardDelights': '보상 기쁨',
            'microInteractions.moreToCome': '더 많은 패턴 예정',
            
            // Code preview
            'codePreview.title': '코드 예제',
            'codePreview.copy': '복사',
            'codePreview.copied': '복사됨!',
            
            // Live preview
            'livePreview.title': '라이브 미리보기',
            'livePreview.comingSoon': '미리보기 곧 출시',
            
            // Footer
            'footer.description': '버즈빌의 디자인 진실의 원천이 되는 곳입니다. 우리는 공개적으로 구축합니다. 이 포털은 주로 내부적으로 그리고 파트너들이 사용하도록 의도되었지만, 우리가 어떻게 일하는지 누구나 살펴볼 수 있기를 좋아합니다!',
            'footer.foundations.mission': '미션',
            'footer.foundations.philosophy': '마인드셋',
            'footer.foundations.values': '작업 원칙',
            'footer.foundations.team': '우리의 팀',
            'footer.foundations.tools': '우리의 스택',
            'footer.brand.principles': '원칙',
            'footer.brand.guidelines': '가이드라인',
            'footer.brand.resources': '리소스',
            'footer.product.principles': '원칙',
            'footer.product.guidelines': '가이드라인',
            'footer.product.resources': '리소스',
            'footer.connect.buzzvil': '버즈빌',
            'footer.connect.contact': '연락처',
            'footer.connect.careers': '채용',
            'footer.connect.figma': 'Figma',
            'footer.connect.github': 'GitHub',
            'footer.connect.linkedin': 'LinkedIn',
            'footer.made': '만든',
            'footer.by': '버즈빌 디자인 팀',
            'footer.privacy': '개인정보 보호정책',
            'footer.terms': '서비스 약관',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ko')) {
      setLanguage(savedLanguage);
    } else {
      // Auto-detect browser language if no saved preference
      const browserLanguage = navigator.language || navigator.languages?.[0] || 'en';
      const detectedLanguage = browserLanguage.startsWith('ko') ? 'ko' : 'en';
      setLanguage(detectedLanguage);
    }
  }, []);

  useEffect(() => {
    // Save language to localStorage when it changes
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const getFontClass = (): string => {
    return language === 'ko' ? 'font-pretendard' : 'font-nunito';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getFontClass }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
